ServerEvents.recipes(event => {
  function baking(output, input) {
    event.custom({
      type: 'clayworks:baking',
      cookingTime: 100,
      ingredient: [ { item: input } ],
      result: output
    })
  }

  // remove recipes
  event.remove({ type: 'create:sandpaper_polishing' })
  event.remove({ type: 'create:milling' })
  event.remove({ type: 'create:mechanical_crafting' })
  event.remove({ type: 'create:haunting' })
  event.remove({ type: 'create:compacting' })
  event.remove({ type: 'create:filling' })
  event.remove({ type: 'create:cutting' })
  event.remove({ type: 'create:deploying' })
  event.remove({ type: 'create:splashing' })
  event.remove({ type: 'create:emptying' })
  event.remove({ type: 'farmersdelight:cutting' })
  event.remove({ type: 'farmersdelight:cooking' })
  event.remove({ type: 'sullysmod:grindstone_polishing' })

  event.remove({ output: 'buzzier_bees:crystallized_honey_block' })
  event.remove({ output: 'buzzier_bees:honey_lamp' })
  event.remove({ output: 'caverns_and_chasms:lava_lamp' })
  event.remove({ output: 'minecraft:chain' })
  event.remove({ output: 'minecraft:calcite' })
  event.remove({ output: 'architects_palette:nether_brass_chain' })
  event.remove({ output: 'create:brass_hand' })
  event.remove({ output: 'caverns_and_chasms:sanguine_plating' })
  event.remove({ output: 'caverns_and_chasms:tuning_fork' })
  event.remove({ output: 'create:andesite_alloy' })
  event.remove({ output: 'create:track' })
  event.remove({ output: 'create:railway_casing' })
  event.remove({ output: 'create:sturdy_sheet' })
  event.remove({ output: 'create:experience_nugget' })
  event.remove({ output: 'create:crushed_raw_zinc' })
  event.remove({ output: 'create:crushed_raw_iron' })
  event.remove({ output: 'create:crushed_raw_gold' })
  event.remove({ output: 'create:crushed_raw_copper' })
  event.remove({ output: 'create:bar_of_chocolate' })
  event.remove({ output: 'create:chocolate_glazed_berries' })
  event.remove({ output: 'minecraft:popped_chorus_fruit' })
  event.remove({ id: 'create:crafting/materials/copper_ingot' })
  event.remove({ id: 'create:crafting/appliances/slime_ball' })
  event.remove({ output: 'minecraft:bread' })
  event.remove({ output: 'create:dough' })
  event.remove({ output: 'create:copper_casing' })
  event.remove({ id: 'create:crushing/amethyst_cluster' })
  event.remove({ id: 'create:crushing/amethyst_block' })
  event.remove({ id: 'create:crushing/glowstone' })
  event.remove({ id: 'create:crushing/blaze_rod' })
  event.remove({ id: 'create:crushing/nether_wart_block' })
  event.remove({ id: 'create:mixing/tea' })
  event.remove({ id: 'create:mixing/chocolate' })
  event.remove({ id: 'create:mixing/chocolate_melting' })
  event.remove({ id: 'create:mixing/mud_by_mixing' })
  event.remove({ id: 'create:mixing/honey' })
  event.remove({ id: 'create:emptying/honey_bottle' })
  event.remove({ id: 'create:pressing/path' })
  event.remove({ output: 'minecraft:quartz', type: 'create:crushing' });
  event.remove({ output: 'minecraft:daylight_detector' })
  event.remove({ output: 'create:andesite_bars' })
  event.remove({ output: 'create:brass_bars' })
  event.remove({ output: 'minecraft:glass_pane', type: 'minecraft:smelting' })
  event.remove({ id: 'create:smelting/glass_from_tiled_glass' })
  event.remove({ id: 'create:smelting/glass_from_framed_glass' })
  event.remove({ id: 'create:smelting/glass_from_horizontal_framed_glass' })
  event.remove({ id: 'create:smelting/glass_from_vertical_framed_glass' })
  event.remove({ output: 'minecraft:nether_wart_block' })
  event.remove({ output: 'minecraft:powered_rail' })
  event.remove({ id: 'environmental:mud_ball' })
  event.remove({ output: 'minecraft:pumpkin_pie' })
  event.remove({ id: 'farmersdelight:milk_bucket_from_bottles' })
  event.remove({ id: 'farmersdelight:pumpkin_from_slices' })
  event.remove({ id: 'minecraft:pumpkin_seeds' })
  event.remove({ output: 'clash:spear' })
  event.remove({ output: 'clash:rod_of_gales' })
  event.remove({ output: 'farmersdelight:organic_compost' })
  event.remove({ id: 'environmental:blue_dye_from_bluebell' })
  event.remove({ output: 'farmersdelight:pie_crust' })
  event.remove({ output: 'farmersdelight:cabbage_leaf' })
  event.remove({ output: 'minecraft:beetroot_soup' })
  event.remove({ output: 'minecraft:rabbit_stew' })
  event.remove({ output: 'minecraft:mushroom_stew' })
  event.remove({ output: 'incubation:scrambled_eggs' })
  event.remove({ output: 'autumnity:pancake' })
  event.remove({ output: 'atmospheric:currant_muffin' })
  event.remove({ id: 'windswept:christmas_pudding' })
  event.remove({ id: 'atmospheric:yucca_gateau' })
  event.remove({ id: 'minecraft:brown_dye' })
  event.remove({ output: 'atmospheric:orange_pudding' })
  event.remove({ id: 'minecraft:netherite_ingot' })
  event.remove({ id: 'caverns_and_chasms:necromium_ingot' })
  event.remove({ output: 'minecraft:coarse_dirt' })
  event.remove({ output: 'caverns_and_chasms:rocky_dirt' })
  event.remove({ id: 'create:crushing/tuff' })
  event.remove({ id: 'create:crushing/tuff_recycling' })
  event.remove({ id: 'minecraft:lead' })
  event.remove({ id: 'minecraft:scaffolding' })
  event.remove({ id: 'minecraft:painting' })
  event.remove({ output: 'farmersdelight:melon_popsicle' })
  event.remove({ output: 'farmersdelight:melon_juice' })
  event.remove({ id: 'farmersdelight:cabbage_from_leaves' })
  event.remove({ id: 'farmersdelight:paper_from_tree_bark' })
  event.remove({ id: 'minecraft:mossy_cobblestone_from_vine' })
  event.remove({ id: 'minecraft:mossy_cobblestone' })
  event.remove({ id: 'minecraft:mossy_stone_bricks_from_vine' })
  event.remove({ id: 'caverns_and_chasms:mossy_cobblestone_bricks_from_vine' })
  event.remove({ id: 'caverns_and_chasms:mossy_cobblestone_tiles_from_vine' })
  event.remove({ id: 'caverns_and_chasms:tuff' })
  event.remove({ id: 'create:tuff_from_stone_types_tuff_stonecutting' })
  event.remove({ output: 'minecraft:shulker_box' })
  event.remove({ output: 'minecraft:lodestone' })
  event.remove({ output: 'windswept:shale' })
  event.remove({ output: 'berry_good:sweet_berry_mince' })
  event.remove({ output: 'berry_good:glowgurt' })
  event.remove({ output: 'atmospheric:passion_fruit_sorbet' })
  event.remove({ output: 'atmospheric:orange_sorbet' })
  event.remove({ output: 'windswept:wild_berry_juice' })
  event.remove({ output: 'minecraft:bundle' })
  event.remove({ id: 'create:pressing/compat/environmental/mycelium_path' })
  event.remove({ id: 'neapolitan:ice' })
  event.remove({ output: 'neapolitan:vanilla_ice_cream' })
  event.remove({ output: 'neapolitan:strawberry_ice_cream' })
  event.remove({ output: 'neapolitan:banana_ice_cream' })
  event.remove({ id: 'create:crushing/compat/neapolitan/ice' })
  event.remove({ output: 'neapolitan:vanilla_pudding' })
  event.remove({ id: 'neapolitan:vanilla/vanilla_cake' })
  event.remove({ id: 'neapolitan:strawberry/strawberry_cake' })
  event.remove({ id: 'neapolitan:banana/banana_cake' })
  event.remove({ output: 'neapolitan:strawberry_banana_smoothie' })
  event.remove({ output: 'windswept:snow_boots' })
  event.remove({ id: 'create:emptying/compat/neapolitan/milk_bottle' })
  event.remove({ id: 'create:emptying/compat/farmersdelight/milk_bottle' })
  event.remove({ id: 'minecraft:sugar_from_sugar_cane' })
  event.remove({ output: 'create:copper_diving_boots' })
  event.remove({ output: 'undead_unleashed:grave_metal_ingot' })
  event.remove({ output: 'undead_unleashed:grave_metal_chestplate' })
  event.remove({ output: 'undead_unleashed:grave_metal_leggings' })
  event.remove({ output: 'undead_unleashed:grave_metal_boots' })
  event.remove({ output: 'undead_unleashed:moonlight_greatsword' })
  event.remove({ output: 'undead_unleashed:tome_of_reflection' })
  event.remove({ output: 'undead_unleashed:shadow_helmet' })
  event.remove({ output: 'undead_unleashed:shadow_chestplate' })
  event.remove({ output: 'undead_unleashed:shadow_leggings' })
  event.remove({ output: 'undead_unleashed:shadow_boots' })
  event.remove({ id: 'undead_unleashed:bonemeal_craft_alt' })
  event.remove({ id: 'undead_unleashed:trident_crafting' })
  event.remove({ output: 'savage_and_ravage:blast_proof_plating' })
  event.remove({ id: 'neapolitan:milk/milk_bottles_from_bucket' })
  event.remove({ id: 'neapolitan:milk/milk_bottles_from_bucket' })
  event.remove({ output: 'minecraft:trapped_chest' })
  event.remove({ input: 'minecraft:tripwire_hook', mod: 'woodworks' })
  event.remove({ input: 'minecraft:tripwire_hook', mod: 'windswept' })
  event.remove({ input: 'minecraft:tripwire_hook', mod: 'environmental' })
  event.remove({ input: 'minecraft:tripwire_hook', mod: 'atmospheric' })
  event.remove({ input: 'minecraft:tripwire_hook', mod: 'upgrade_aquatic' })
  event.remove({ output: 'autumnity:maple_trapped_chest' })
  event.remove({ output: 'caverns_and_chasms:azalea_trapped_chest' })
  event.remove({ output: 'atmospheric:dolerite' })
  event.remove({ id: 'caverns_and_chasms:golden_milk_bucket' })
  event.remove({ id: 'environmental:red_dye_from_red_hibiscus' })
  event.remove({ id: 'environmental:orange_dye_from_orange_hibiscus' })
  event.remove({ output: 'environmental:hibiscus_leaves' })
  event.remove({ output: 'environmental:hibiscus_leaf_pile' })
  event.remove({ output: 'sullysmod:jade_shield' })
  event.remove({ output: 'sullysmod:polished_chiseled_jade' })
  event.remove({ output: 'caverns_and_chasms:lapis_lamp' })
  event.remove({ output: 'caverns_and_chasms:spinel_lamp' })
  event.remove({ output: 'caverns_and_chasms:lapis_bricks' })
  event.remove({ output: 'caverns_and_chasms:spinel_bricks' })
  event.remove({ id: 'sullysmod:stonecutting/polished_jade_bricks_from_polished_jade_block_stonecutting' })
  event.remove({ output: 'farmersdelight:canvas_sign' })
  event.remove({ output: 'cataclysm:abyssal_sacrifice' })
  event.remove({ output: 'cataclysm:monstrous_eye' })
  event.remove({ output: 'cataclysm:flame_eye' })
  event.remove({ output: 'cataclysm:abyss_eye' })
  event.remove({ output: 'clash:greatblade' })
  event.remove({ output: 'create:goggles' })
  event.remove({ id: 'cataclysm:bloom_stone_pauldrons' })
  event.remove({ id: 'cataclysm:smithing/monstrous_helm' })
  event.remove({ output: 'cataclysm:ancient_metal_ingot' })
  event.remove({ output: 'cataclysm:ancient_metal_nugget' })
  event.remove({ output: 'cataclysm:bone_reptile_helmet' })
  event.remove({ output: 'cataclysm:ancient_spear' })
  event.remove({ id: 'architects_palette:nether_brass_block' })
  event.remove({ output: 'architects_palette:coarse_snow' })
  event.remove({ output: 'architects_palette:charcoal_block' })
  event.remove({ id: 'architects_palette:charcoal_from_charcoal_blocks' })
  event.remove({ output: 'architects_palette:spool' })
  event.remove({ id: 'minecraft:bone_meal_from_bone_block' })
  event.remove({ id: 'minecraft:bone_block' })
  event.remove({ output: 'minecraft:red_nether_bricks' })
  event.remove({ output: 'quark:blue_nether_bricks' })
  event.remove({ output: 'architects_palette:molten_nether_bricks' })
  event.remove({ output: 'caverns_and_chasms:flooded_dripstone_shingles' })
  event.remove({ id: 'architects_palette:ender_pearl_from_block' })
  event.remove({ output: 'architects_palette:sunmetal_brick' })
  event.remove({ output: 'architects_palette:sunmetal_block' })
  event.remove({ id: 'cataclysm:bone_meal' })
  event.remove({ output: 'minecraft:iron_nugget', type: 'minecraft:smelting' })
  event.remove({ output: 'minecraft:iron_nugget', type: 'minecraft:blasting' })
  event.remove({ output: 'minecraft:gold_nugget', type: 'minecraft:smelting' })
  event.remove({ output: 'minecraft:gold_nugget', type: 'minecraft:blasting' })
  event.remove({ output: 'caverns_and_chasms:copper_nugget', type: 'minecraft:smelting' })
  event.remove({ output: 'caverns_and_chasms:copper_nugget', type: 'minecraft:blasting' })
  event.remove({ output: 'caverns_and_chasms:silver_nugget', type: 'minecraft:smelting' })
  event.remove({ output: 'caverns_and_chasms:silver_nugget', type: 'minecraft:blasting' })
  event.remove({ output: 'environmental:pine_hedge' })
  event.remove({ output: 'environmental:pine_post' })
  event.remove({ output: 'environmental:pine_boards' })
  event.remove({ output: 'environmental:stripped_pine_post' })
  event.remove({ output: 'environmental:pine_bookshelf' })
  event.remove({ output: 'environmental:pine_beehive' })
  event.remove({ output: 'environmental:pine_leaves' })
  event.remove({ output: 'environmental:pine_chest' })
  event.remove({ output: 'quark:polished_limestone_slab' })
  event.remove({ output: 'quark:limestone_slab' })
  event.remove({ output: 'quark:polished_limestone' })
  event.remove({ output: 'quark:limestone_stairs' })
  event.remove({ output: 'quark:limestone_wall' })
  event.remove({ output: 'quark:polished_limestone_stairs' })
  event.remove({ output: 'quark:polished_shale_slab' })
  event.remove({ output: 'quark:shale_slab' })
  event.remove({ output: 'quark:polished_shale' })
  event.remove({ output: 'quark:shale_stairs' })
  event.remove({ output: 'quark:shale_wall' })
  event.remove({ output: 'quark:polished_shale_stairs' })
  event.remove({ output: 'woodworks:acacia_chest' })
  event.remove({ output: 'woodworks:jungle_chest' })
  event.remove({ output: 'woodworks:mangrove_chest' })
  event.remove({ output: 'minecraft:acacia_leaves' })
  event.remove({ output: 'minecraft:jungle_leaves' })
  event.remove({ output: 'minecraft:mangrove_leaves' })
  event.remove({ output: 'woodworks:mangrove_beehive' })
  event.remove({ output: 'woodworks:acacia_beehive' })
  event.remove({ output: 'woodworks:jungle_beehive' })
  event.remove({ output: 'woodworks:mangrove_bookshelf' })
  event.remove({ output: 'woodworks:acacia_bookshelf' })
  event.remove({ output: 'woodworks:jungle_bookshelf' })
  event.remove({ output: 'woodworks:mangrove_boards' })
  event.remove({ output: 'woodworks:acacia_boards' })
  event.remove({ output: 'woodworks:jungle_boards' })
  event.remove({ output: 'minecraft:tipped_arrow' })
  event.remove({ output: 'minecraft:coal', type: 'minecraft:blasting' })
  event.remove({ output: 'minecraft:coal', type: 'minecraft:smelting' })
  event.remove({ output: 'minecraft:lapis_lazuli', type: 'minecraft:blasting' })
  event.remove({ output: 'minecraft:lapis_lazuli', type: 'minecraft:smelting' })
  event.remove({ output: 'minecraft:diamond', type: 'minecraft:blasting' })
  event.remove({ output: 'minecraft:diamond', type: 'minecraft:smelting' })
  event.remove({ output: 'caverns_and_chasms:spinel', type: 'minecraft:blasting' })
  event.remove({ output: 'caverns_and_chasms:spinel', type: 'minecraft:smelting' })
  event.remove({ id: 'minecraft:iron_ingot_from_smelting_iron_ore' })
  event.remove({ id: 'minecraft:iron_ingot_from_smelting_deepslate_iron_ore' })
  event.remove({ id: 'create:smelting/iron_ingot_from_crushed' })
  event.remove({ id: 'minecraft:iron_ingot_from_blasting_iron_ore' })
  event.remove({ id: 'minecraft:iron_ingot_from_blasting_deepslate_iron_ore' })
  event.remove({ id: 'create:blasting/iron_ingot_from_crushed' })
  event.remove({ id: 'minecraft:copper_ingot_from_smelting_copper_ore' })
  event.remove({ id: 'minecraft:copper_ingot_from_smelting_deepslate_copper_ore' })
  event.remove({ id: 'create:smelting/copper_ingot_from_crushed' })
  event.remove({ id: 'minecraft:copper_ingot_from_blasting_copper_ore' })
  event.remove({ id: 'minecraft:copper_ingot_from_blasting_deepslate_copper_ore' })
  event.remove({ id: 'create:blasting/copper_ingot_from_crushed' })
  event.remove({ id: 'minecraft:gold_ingot_from_smelting_gold_ore' })
  event.remove({ id: 'minecraft:gold_ingot_from_smelting_deepslate_gold_ore' })
  event.remove({ id: 'minecraft:gold_ingot_from_smelting_nether_gold_ore' })
  event.remove({ id: 'create:smelting/gold_ingot_from_crushed' })
  event.remove({ id: 'minecraft:gold_ingot_from_blasting_gold_ore' })
  event.remove({ id: 'minecraft:gold_ingot_from_blasting_deepslate_gold_ore' })
  event.remove({ id: 'minecraft:gold_ingot_from_blasting_nether_gold_ore' })
  event.remove({ id: 'create:blasting/gold_ingot_from_crushed' })
  event.remove({ id: 'create:smelting/zinc_ingot_from_ore' })
  event.remove({ id: 'create:smelting/zinc_ingot_from_crushed' })
  event.remove({ id: 'create:blasting/zinc_ingot_from_ore' })
  event.remove({ id: 'create:blasting/zinc_ingot_from_crushed' })
  event.remove({ id: 'caverns_and_chasms:silver_ingot_from_blasting_silver_ore' })
  event.remove({ id: 'caverns_and_chasms:silver_ingot_from_blasting_deepslate_silver_ore' })
  event.remove({ id: 'caverns_and_chasms:silver_ingot_from_blasting_soul_silver_ore' })
  event.remove({ id: 'caverns_and_chasms:silver_ingot_from_smelting_silver_ore' })
  event.remove({ id: 'caverns_and_chasms:silver_ingot_from_smelting_deepslate_silver_ore' })
  event.remove({ id: 'caverns_and_chasms:silver_ingot_from_smelting_soul_silver_ore' })
  event.remove({ output: 'quark:moss_paste' })
  event.remove({ output: 'quark:framed_glass' })
  event.remove({ output: 'quark:midori_block' })
  event.remove({ id: 'queen_bee:stinger_sword' })
  event.remove({ output: 'supplementaries:goblet' })
  event.remove({ output: 'mace_backport:mace' })
  event.remove({ output: 'supplementaries:wind_vane' })
  event.remove({ output: 'irons_spellbooks:cooldown_ring' })
  event.remove({ output: 'irons_spellbooks:cast_time_ring' })
  event.remove({ output: 'irons_spellbooks:fireward_ring' })
  event.remove({ id: 'irons_spellbooks:hogskin_to_leather' })
  event.remove({ id: 'irons_spellbooks:lesser_spell_slot_upgrade' })

  // edit recipes
  event.replaceOutput({ output: 'minecraft:quartz' }, 'minecraft:quartz', 'minecraft:charcoal')
  event.replaceOutput({ input: 'environmental:yellow_hibiscus' }, 'minecraft:yellow_dye', 'minecraft:white_dye')
  event.replaceOutput({ input: 'environmental:magenta_hibiscus' }, 'minecraft:magenta_dye', 'minecraft:light_blue_dye')
  event.replaceInput({ input: 'irons_spellbooks:arcane_essence' }, 'irons_spellbooks:arcane_essence', 'minecraft:lapis_lazuli')
  event.replaceInput({ output: 'irons_spellbooks:mana_ring' }, 'irons_spellbooks:arcane_ingot', 'caverns_and_chasms:silver_ingot')
  event.replaceInput({ output: 'irons_spellbooks:mana_ring' }, 'minecraft:diamond', 'minecraft:diamond_block')
  event.replaceInput({ output: 'irons_spellbooks:amethyst_resonance_charm' }, 'minecraft:leather', 'farmersdelight:rope')
  event.replaceInput({ input: 'create:andesite_alloy' }, 'create:andesite_alloy', 'create:zinc_ingot')
  event.replaceInput({ input: 'minecraft:redstone' }, 'minecraft:redstone', 'kubejs:copper_wire')
  event.replaceInput({ input: 'create:electron_tube' }, 'create:electron_tube', 'kubejs:power_coil')
  event.replaceInput({ input: 'minecraft:quartz' }, 'minecraft:quartz', 'minecraft:amethyst_shard')
  event.replaceInput({ input: '#forge:salad_ingredients' }, '#forge:salad_ingredients', 'farmersdelight:cabbage')
  event.replaceInput({ input: '#forge:milk' }, '#forge:milk', '#forge:buckets/milk')
  event.replaceInput({ input: 'architects_palette:nether_brass_ingot' }, 'architects_palette:nether_brass_ingot', 'create:brass_ingot')
  event.replaceInput({ input: 'architects_palette:nether_brass_nugget' }, 'architects_palette:nether_brass_nugget', 'create:brass_nugget')
  event.replaceInput({ output: 'create:mechanical_arm' }, 'create:zinc_ingot', 'create:brass_hand')
  event.replaceInput({ output: 'minecraft:bucket' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'create:weighted_ejector' }, 'create:golden_sheet', 'kubejs:silver_sheet')
  event.replaceInput({ output: 'caverns_and_chasms:toolbox' }, 'minecraft:copper_ingot', 'caverns_and_chasms:copper_nugget')
  event.replaceInput({ output: 'caverns_and_chasms:toolbox' }, 'minecraft:copper_block', 'create:copper_sheet')
  event.replaceInput({ output: 'create:item_vault' }, 'create:iron_sheet', 'kubejs:silver_sheet')
  event.replaceInput({ output: 'create:super_glue' }, 'minecraft:iron_nugget', 'caverns_and_chasms:copper_nugget')
  event.replaceInput({ output: 'create:super_glue' }, 'create:iron_sheet', 'create:copper_sheet')
  event.replaceInput({ output: 'create:redstone_contact' }, 'create:iron_sheet', 'create:copper_sheet')
  event.replaceInput({ output: 'autumnity:pumpkin_bread' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'neapolitan:banana_bread' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'minecraft:tripwire_hook' }, 'minecraft:iron_ingot', 'kubejs:zinc_sheet')
  event.replaceInput({ output: 'minecraft:lever' }, 'minecraft:cobblestone', 'create:zinc_ingot')
  event.replaceInput({ output: 'minecraft:smithing_table' }, 'minecraft:iron_ingot', 'caverns_and_chasms:silver_ingot')
  event.replaceInput({ output: 'minecraft:clock' }, 'minecraft:gold_ingot', 'create:golden_sheet')
  event.replaceInput({ output: 'minecraft:compass' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'caverns_and_chasms:barometer' }, 'minecraft:copper_ingot', 'create:copper_sheet')
  event.replaceInput({ output: 'caverns_and_chasms:depth_gauge' }, 'caverns_and_chasms:silver_ingot', 'kubejs:silver_sheet')
  event.replaceInput({ output: 'create:basin' }, 'create:zinc_ingot', 'minecraft:iron_ingot')
  event.replaceInput({ output: 'minecraft:minecart' }, 'minecraft:iron_ingot', 'create:zinc_ingot')
  event.replaceInput({ output: 'minecraft:redstone_lamp' }, 'kubejs:copper_wire', 'minecraft:glowstone_dust')
  event.replaceInput({ output: 'minecraft:redstone_lamp' }, 'minecraft:glowstone', 'kubejs:copper_wire')
  event.replaceInput({ output: 'minecraft:rail' }, 'minecraft:iron_nugget', 'create:zinc_nugget')
  event.replaceInput({ output: 'minecraft:activator_rail' }, 'minecraft:iron_nugget', 'caverns_and_chasms:copper_nugget')
  event.replaceInput({ output: 'minecraft:activator_rail' }, 'minecraft:redstone_torch', 'kubejs:power_coil')
  event.replaceInput({ output: 'minecraft:brewing_stand' }, 'minecraft:blaze_rod', 'upgrade_aquatic:prismarine_rod')
  event.replaceInput({ output: 'minecraft:brewing_stand' }, 'caverns_and_chasms:silver_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'minecraft:note_block' }, 'kubejs:copper_wire', 'create:brass_ingot')
  event.replaceInput({ output: 'create:redstone_contact' }, 'kubejs:copper_wire', 'kubejs:power_coil')
  event.replaceInput({ output: 'create:stockpile_switch' }, 'minecraft:comparator', 'create:portable_storage_interface')
  event.replaceInput({ output: 'minecraft:heavy_weighted_pressure_plate' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'minecraft:light_weighted_pressure_plate' }, 'minecraft:gold_ingot', 'create:golden_sheet')
  event.replaceInput({ output: 'caverns_and_chasms:medium_weighted_pressure_plate' }, 'caverns_and_chasms:silver_ingot', 'kubejs:silver_sheet')
  event.replaceInput({ output: 'create:sticker' }, 'kubejs:copper_wire', 'kubejs:power_coil')
  event.replaceInput({ output: 'neapolitan:strawberry_scones' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'windswept:mutton_pie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'windswept:lavender_scones' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'windswept:wild_berry_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'windswept:gingerbread_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'farmersdelight:honey_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'farmersdelight:sweet_berry_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'abnormals_delight:cherry_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'abnormals_delight:maple_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'abnormals_delight:mulberry_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'farmersdelight:skillet' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'create:rope_pulley' }, '#minecraft:wool', 'farmersdelight:rope')
  event.replaceInput({ output: 'minecraft:stonecutter' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'woodworks:sawmill' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'minecraft:sea_lantern' }, 'minecraft:prismarine_shard', 'upgrade_aquatic:prismarine_rod')
  event.replaceInput({ output: 'windswept:frost_arrow' }, 'minecraft:stick', 'kubejs:ice_rod')
  event.replaceInput({ output: 'windswept:frost_arrow' }, 'windswept:icicles', 'minecraft:feather')
  event.replaceInput({ output: 'heart_crystals:heart_lantern' }, 'minecraft:iron_nugget', 'caverns_and_chasms:silver_nugget')
  event.replaceInput({ output: 'create:filter' }, '#minecraft:wool', 'farmersdelight:canvas')
  event.replaceInput({ output: 'create:filter' }, 'minecraft:iron_nugget', 'create:zinc_nugget')
  event.replaceInput({ output: 'create:attribute_filter' }, '#minecraft:wool', 'farmersdelight:canvas')
  event.replaceInput({ output: 'farmersdelight:flint_knife' }, 'minecraft:flint', '#minecraft:planks')
  event.replaceInput({ output: 'endermanoverhaul:corrupted_shield' }, 'minecraft:iron_ingot', 'create:brass_ingot')
  event.replaceInput({ output: 'create:wrench' }, 'create:golden_sheet', 'create:brass_sheet')
  event.replaceInput({ output: 'farmersdelight:roasted_mutton_chops' }, 'farmersdelight:cooked_mutton_chops', 'minecraft:cooked_mutton')
  event.replaceInput({ output: 'create:clockwork_bearing' }, 'kubejs:power_coil', 'minecraft:clock')
  event.replaceInput({ output: 'minecraft:loom' }, 'minecraft:string', 'farmersdelight:canvas')
  event.replaceInput({ output: 'minecraft:recovery_compass' }, 'minecraft:echo_shard', 'caverns_and_chasms:spinel')
  event.replaceInput({ output: 'minecraft:fire_charge' }, 'minecraft:blaze_powder', 'undead_unleashed:charstone_shard')
  event.replaceInput({ output: 'savage_and_ravage:gloomy_tiles' }, 'minecraft:phantom_membrane', 'undead_unleashed:cursed_cloth')
  event.replaceInput({ output: 'echoplus:echo_shield' }, 'minecraft:sculk_catalyst', 'minecraft:echo_shard')
  event.replaceInput({ output: 'sullysmod:lanternfish_roll' }, 'sullysmod:lanternfish_slice', 'sullysmod:lanternfish')
  event.replaceInput({ output: 'sullysmod:jade_totem' }, 'sullysmod:polished_jade_shingles', 'sullysmod:polished_jade')
  event.replaceInput({ output: 'sullysmod:jade_flinger_totem' }, 'sullysmod:polished_jade_shingles', 'sullysmod:polished_jade')
  event.replaceInput({ output: 'sullysmod:polished_jade_bricks' }, 'sullysmod:polished_jade_block', 'sullysmod:polished_jade')
  event.replaceInput({ output: 'sullysmod:polished_jade_pillar' }, 'sullysmod:polished_jade_block', 'sullysmod:polished_jade_bricks')
  event.replaceInput({ output: 'create:nozzle' }, '#minecraft:wool', 'farmersdelight:canvas')
  event.replaceInput({ output: 'minecraft:ender_eye' }, 'minecraft:blaze_powder', 'architects_palette:withered_bone')
  event.replaceInput({ output: 'create:mechanical_drill' }, 'create:zinc_ingot', 'kubejs:zinc_sheet')
  event.replaceInput({ output: 'create:mechanical_plough' }, 'create:zinc_ingot', 'kubejs:zinc_sheet')
  event.replaceInput({ output: 'create:cart_assembler' }, 'create:zinc_ingot', 'kubejs:zinc_sheet')
  event.replaceInput({ output: 'create:sticker' }, 'create:zinc_ingot', 'kubejs:zinc_sheet')
  event.replaceInput({ output: 'minecraft:arrow' }, 'minecraft:flint', '#minecraft:planks')
  event.replaceInput({ output: 'minecraft:conduit' }, 'minecraft:heart_of_the_sea', 'upgrade_aquatic:elder_eye')
  event.replaceInput({ id: 'create:crafting/materials/brass_ingot_from_decompacting' }, 'create:brass_block', 'architects_palette:nether_brass_block')
  event.replaceInput({ output: 'architects_palette:calcite_lamp' }, 'minecraft:glow_ink_sac', 'minecraft:echo_shard')
  event.replaceInput({ output: 'architects_palette:dripstone_pillar' }, 'architects_palette:dripstone_bricks', 'caverns_and_chasms:dripstone_shingles')
  event.replaceInput({ output: 'architects_palette:dripstone_lamp' }, 'minecraft:dripstone_block', 'caverns_and_chasms:dripstone_shingles')
  event.replaceInput({ output: 'architects_palette:calcite_lamp' }, 'minecraft:calcite', 'caverns_and_chasms:polished_calcite')
  event.replaceInput({ output: 'architects_palette:tuff_lamp' }, 'minecraft:tuff', 'caverns_and_chasms:polished_tuff')
  event.replaceInput({ output: 'quark:trowel' }, 'minecraft:iron_ingot', 'kubejs:zinc_sheet')
  event.replaceInput({ output: 'minecraft:shears' }, 'minecraft:iron_ingot', 'create:zinc_ingot')
  event.replaceInput({ output: 'minecraft:furnace' }, '#forge:cobblestone', 'minecraft:cobblestone')
  event.replaceInput({ output: 'create:minecart_coupling' }, 'create:iron_sheet', 'kubejs:zinc_sheet')
  event.replaceInput({ output: 'create:minecart_coupling' }, 'create:zinc_ingot', 'minecraft:iron_ingot')
  event.replaceInput({ output: 'minecraft:glow_item_frame' }, 'minecraft:glow_ink_sac', 'minecraft:glow_berries')
  event.replaceInput({ output: 'quark:glowing_glass_item_frame' }, 'minecraft:glow_ink_sac', 'minecraft:glow_berries')
  event.replaceInput({ output: '#supplementaries:sconces' }, 'minecraft:iron_nugget', 'create:zinc_nugget')
  event.replaceInput({ output: 'caverns_and_chasms:brazier' }, '#minecraft:coals', 'minecraft:torch')
  event.replaceInput({ output: 'caverns_and_chasms:soul_brazier' }, '#minecraft:soul_fire_base_blocks', 'minecraft:soul_torch')
  event.replaceInput({ output: 'caverns_and_chasms:cupric_brazier' }, 'minecraft:copper_ingot', 'caverns_and_chasms:cupric_torch')

  // add recipes
  event.shapeless('minecraft:bread', ['create:wheat_flour', 'create:wheat_flour', 'create:wheat_flour'])
  event.shapeless('minecraft:slime_ball', ['autumnity:snail_goo', 'minecraft:lime_dye'])
  event.shapeless(Item.of('buzzier_bees:honey_lamp', 2), ['minecraft:blaze_rod', 'minecraft:honey_bottle', 'create:golden_sheet'])
  event.shaped(Item.of('caverns_and_chasms:lava_lamp', 2), ['S', 'L', 'S'], { S: 'create:golden_sheet', L: '#forge:buckets/lava' })
  event.shaped('minecraft:chain', ['N', 'N', 'N'], { N: 'minecraft:iron_nugget' })
  event.shaped('architects_palette:nether_brass_chain', ['N', 'N', 'N'], { N: 'create:brass_nugget' })
  event.shaped('create:brass_hand', [' B ', 'BBB', ' S '], { B: 'create:brass_ingot', S: 'kubejs:silver_sheet' })
  event.shapeless('caverns_and_chasms:sanguine_plating', ['kubejs:silver_sheet', '#rrm:rotten_flesh', 'heart_crystals:heart_crystal_shard'])
  event.shaped('create:crushing_wheel', ['III', 'ICI', 'III'], { I: 'minecraft:iron_ingot', C: 'create:large_cogwheel' })
  event.shaped('caverns_and_chasms:tuning_fork', [' S ', ' IS', 'I  '], { S: 'create:copper_sheet', I: 'minecraft:copper_ingot' })
  event.shaped(Item.of('kubejs:copper_wire', 2), ['CIC'], { C: 'caverns_and_chasms:copper_nugget', I: 'minecraft:copper_ingot' })
  event.shaped('minecraft:elytra', ['F F', 'FFF', 'F F'], { F: 'kubejs:torn_elytra_fragment' })
  event.shaped('kubejs:power_coil', ['CCC', 'CWC', 'CCC'], { C: 'undead_unleashed:charstone_shard', W: 'kubejs:copper_wire' })
  event.shaped('minecraft:daylight_detector', ['GG', 'SS'], { G: 'minecraft:glass', S: 'create:copper_sheet' })
  event.shaped(Item.of('create:andesite_bars', 16), ['III', 'III'], { I: 'create:zinc_ingot' })
  event.shaped(Item.of('create:brass_bars', 16), ['III', 'III'], { I: 'create:brass_ingot' })
  event.shapeless('minecraft:crying_obsidian', ['minecraft:obsidian', 'minecraft:amethyst_shard'])
  event.shaped(Item.of('minecraft:powered_rail', 3), ['NSN', 'NCN', 'NSN'], { N: 'minecraft:gold_nugget', S: 'minecraft:stick', C: 'kubejs:power_coil' })
  event.shapeless('environmental:lumberer_banner_pattern', ['minecraft:paper', 'windswept:pinecone'])
  event.shapeless('minecraft:flint', ['minecraft:gravel'])
  event.shapeless(Item.of('farmersdelight:raw_pasta', 2), ['#forge:eggs', 'create:wheat_flour', 'create:wheat_flour'])
  event.shapeless('minecraft:pumpkin_pie', ['farmersdelight:pumpkin_slice', 'farmersdelight:pumpkin_slice', 'create:wheat_flour', 'minecraft:sugar', '#forge:eggs'])
  event.shaped('minecraft:pumpkin', ['SSS', 'SSS', 'SSS'], { S: 'farmersdelight:pumpkin_slice' })
  event.shaped('otherworldly_accessories:totem_of_regeneration', ['PPP', 'PHP', ' P '], { P: 'windswept:pinecone', H: 'heart_crystals:heart_crystal' })
  event.shapeless('upgrade_aquatic:pink_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:pink_dye'])
  event.shapeless('upgrade_aquatic:purple_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:purple_dye'])
  event.shapeless('upgrade_aquatic:blue_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:light_blue_dye'])
  event.shapeless('upgrade_aquatic:green_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:lime_dye'])
  event.shapeless('upgrade_aquatic:yellow_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:yellow_dye'])
  event.shapeless('upgrade_aquatic:orange_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:orange_dye'])
  event.shapeless('upgrade_aquatic:red_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:red_dye'])
  event.shapeless('upgrade_aquatic:white_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:white_dye'])
  event.shaped(Item.of('endermanoverhaul:icy_pearl', 2), [' I ', 'IPI', ' I '], { P: 'minecraft:ender_pearl', I: 'windswept:icicles' })
  event.shaped(Item.of('endermanoverhaul:summoner_pearl', 2), [' L ', 'LPL', ' L '], { P: 'minecraft:ender_pearl', L: 'minecraft:lapis_lazuli' })
  event.shaped(Item.of('endermanoverhaul:bubble_pearl', 2), [' C ', 'CPC', ' C '], { P: 'minecraft:ender_pearl', C: 'minecraft:prismarine_crystals' })
  event.shaped(Item.of('endermanoverhaul:soul_pearl', 2), [' S ', 'SPS', ' S '], { P: 'minecraft:ender_pearl', S: 'undead_unleashed:lost_soul' })
  event.shaped('kubejs:ice_rod', [' I', 'I '], { I: 'windswept:icicles' })
  event.shapeless(Item.of('autumnity:turkey_piece', 5), ['autumnity:turkey'])
  event.shapeless(Item.of('farmersdelight:bacon', 2), ['minecraft:porkchop'])
  event.shaped('minecraft:shulker_box', ['SSS', 'SCS', 'SSS'], { S: 'minecraft:echo_shard', C: '#forge:chests/wooden' })
  event.shaped('minecraft:lodestone', ['SSS', 'SPS', 'SSS'], { S: 'minecraft:smooth_stone', P: 'minecraft:ender_pearl' })
  event.shaped('minecraft:bundle', ['S', 'L'], { S: 'minecraft:string', L: 'minecraft:leather' })
  event.shaped('artifacts:obsidian_skull', ['OOO', 'OSO', ' O '], { S: 'minecraft:wither_skeleton_skull', O: 'create:powdered_obsidian' })
  event.shaped('clash:rod_of_gales', ['  N', ' S ', 'T  '], { S: 'caverns_and_chasms:spinel', T: 'minecraft:stick', N: 'caverns_and_chasms:silver_nugget' })
  event.shaped('atmospheric:green_aspen_leaves', ['LL', 'LL'], { L: 'atmospheric:green_aspen_leaf_pile' })
  event.shapeless(Item.of('atmospheric:green_aspen_leaf_pile', 4), ['atmospheric:green_aspen_leaves'])
  event.shaped(Item.of('atmospheric:green_aspen_hedge', 2), ['G', 'L'], { L: '#atmospheric:aspen_logs', G: 'atmospheric:green_aspen_leaves' })
  event.shaped(Item.of('caverns_and_chasms:fragile_stone', 16), ['BBB', 'BSB', 'BBB'], { B: 'minecraft:stone', S: 'caverns_and_chasms:spinel' })
  event.shaped(Item.of('caverns_and_chasms:fragile_deepslate', 16), ['DDD', 'DSD', 'DDD'], { D: 'minecraft:deepslate', S: 'caverns_and_chasms:spinel' })
  event.shapeless('undead_unleashed:grave_metal_ingot', ['kubejs:zinc_sheet', 'undead_unleashed:grave_metal_scrap', 'minecraft:bone'])
  event.shapeless(Item.of('undead_unleashed:grave_metal_ingot', 2), ['kubejs:zinc_sheet', 'undead_unleashed:grave_metal_scrap', 'architects_palette:withered_bone'])
  event.shaped('undead_unleashed:grave_metal_helmet', ['GGG', 'G G'], { G: 'undead_unleashed:grave_metal_ingot' })
  event.shaped('undead_unleashed:grave_metal_chestplate', ['G G', 'GGG', 'GGG'], { G: 'undead_unleashed:grave_metal_ingot' })
  event.shaped('undead_unleashed:grave_metal_leggings', ['GGG', 'G G', 'G G'], { G: 'undead_unleashed:grave_metal_ingot' })
  event.shaped('undead_unleashed:grave_metal_boots', ['G G', 'G G'], { G: 'undead_unleashed:grave_metal_ingot' })
  event.shapeless('undead_unleashed:moonlight_greatsword', ['minecraft:diamond_sword', 'caverns_and_chasms:silver_sword', 'undead_unleashed:grave_metal_sword', 'undead_unleashed:lost_soul', 'windswept:nightshade', 'quark:glow_shroom'])
  event.shapeless('windswept:nightshade', ['#minecraft:small_flowers', 'minecraft:lapis_lazuli'])
  event.shaped('undead_unleashed:shadow_helmet', ['GGG', 'G G'], { G: 'undead_unleashed:cursed_cloth' })
  event.shaped('undead_unleashed:shadow_chestplate', ['G G', 'GGG', 'GGG'], { G: 'undead_unleashed:cursed_cloth' })
  event.shaped('undead_unleashed:shadow_leggings', ['GGG', 'G G', 'G G'], { G: 'undead_unleashed:cursed_cloth' })
  event.shaped('undead_unleashed:shadow_boots', ['G G', 'G G'], { G: 'undead_unleashed:cursed_cloth'  })
  event.shapeless(Item.of('undead_unleashed:cursed_cloth', 2), ['minecraft:amethyst_shard', 'atmospheric:grimweb', 'atmospheric:grimweb'])
  event.shapeless('otherworldly_accessories:bottle_o_glinting', ['undead_unleashed:lost_soul', 'windswept:nightshade', 'minecraft:glass_bottle'])
  event.shaped('savage_and_ravage:wand_of_freezing', ['  P', ' R ', 'L  '], { P: 'endermanoverhaul:icy_pearl', R: 'kubejs:ice_rod', L: 'minecraft:lapis_lazuli'  })
  event.shapeless('savage_and_ravage:runed_gloomy_tiles', ['savage_and_ravage:gloomy_tiles', 'undead_unleashed:lost_soul'])
  event.shapeless('savage_and_ravage:blast_proof_plating', ['create:golden_sheet', 'savage_and_ravage:creeper_spores', 'minecraft:gunpowder'])
  event.shaped(Item.of('kubejs:grave_metal_plates', 12), ['PP', 'PP'], { P: 'undead_unleashed:grave_metal_ingot' })
  event.shaped(Item.of('kubejs:grave_metal_plate_stairs', 4), ['P  ', 'PP ', 'PPP'], { P: 'kubejs:grave_metal_plates' })
  event.shaped(Item.of('kubejs:grave_metal_plate_slab', 6), ['PPP'], { P: 'kubejs:grave_metal_plates' })
  event.shaped('caverns_and_chasms:golden_lava_bucket', ['SSS', 'SBS', 'SSS'], { S: 'undead_unleashed:charstone_shard', B: 'caverns_and_chasms:golden_bucket' })
  event.shaped('sullysmod:jade_shield', ['JJJ', 'JSJ', 'JJJ'], { S: 'minecraft:shield', J: 'sullysmod:polished_jade' })
  event.shaped('otherworldly_accessories:battle_horseshoe', ['B B', 'BJB', ' B '], { B: 'create:brass_ingot', J: 'sullysmod:polished_jade' })
  event.shaped('otherworldly_accessories:mount_effigy', ['JJJ', 'JBJ', 'JJJ'], { B: 'otherworldly_accessories:battle_horseshoe', J: 'sullysmod:polished_jade' })
  event.shaped('caverns_and_chasms:spinel_lamp', [' D ', 'DSD', ' D '], { D: 'minecraft:glowstone_dust', S: 'caverns_and_chasms:spinel' })
  event.shaped('caverns_and_chasms:lapis_lamp', [' D ', 'DLD', ' D '], { D: 'minecraft:glowstone_dust', L: 'minecraft:lapis_lazuli' })
  event.shaped('sullysmod:polished_chiseled_jade', [' D ', 'DJD', ' D '], { D: 'minecraft:glowstone_dust', J: 'sullysmod:polished_jade' })
  event.shaped(Item.of('caverns_and_chasms:spinel_bricks', 4), ['SS', 'SS'], { S: 'caverns_and_chasms:spinel' })
  event.shaped(Item.of('caverns_and_chasms:lapis_bricks', 4), ['LL', 'LL'], { L: 'minecraft:lapis_lazuli' })
  event.shapeless('farmersdelight:canvas_sign', ['#minecraft:signs', 'farmersdelight:canvas'])
  event.shaped('cataclysm:abyssal_sacrifice', ['AAA', 'AHA', ' A '], { A: 'minecraft:amethyst_shard', H: 'heart_crystals:heart_crystal' })
  event.shapeless('cataclysm:monstrous_eye', ['minecraft:ender_pearl', 'minecraft:blaze_powder'])
  event.shapeless(Item.of('cataclysm:flame_eye', 2), ['cataclysm:flame_eye', 'minecraft:blaze_powder'])
  event.shaped('cataclysm:khopesh', [' A', 'S '], { A: 'architects_palette:sunmetal_brick', S: 'minecraft:stick' })
  event.shapeless('cataclysm:abyss_eye', ['minecraft:ender_pearl', 'minecraft:crying_obsidian'])
  event.shaped('create:goggles', [' R ', 'ABA'], { R: 'farmersdelight:rope', A: 'minecraft:amethyst_shard', B: 'create:brass_sheet' })
  event.shapeless('architects_palette:sunmetal_brick', ['create:brass_sheet', 'cataclysm:ancient_metal_nugget', 'cataclysm:ancient_metal_nugget'])
  event.shaped('cataclysm:bone_reptile_helmet', ['AAA', 'AHA'], { A: 'architects_palette:sunmetal_brick', H: 'cataclysm:kobolediator_skull'})
  event.shaped('cataclysm:ancient_spear', [' AT', ' AA', 'A  '], { A: 'architects_palette:sunmetal_brick', T: 'kubejs:wadjet_tail'})
  event.shaped('architects_palette:nether_brass_block', ['BBB', 'BBB', 'BBB'], { B: 'create:brass_ingot' })
  event.shaped('architects_palette:monazite_rod', ['SD', 'DS'], { S: 'undead_unleashed:charstone_shard', D: 'minecraft:glowstone_dust' })
  event.shaped('architects_palette:charcoal_block', ['CCC', 'CCC', 'CCC'], { C: 'minecraft:charcoal' })
  event.shapeless(Item.of('minecraft:charcoal', 9), ['architects_palette:charcoal_block'])
  event.shaped('architects_palette:spool', ['SSS', 'SSS', 'SSS'], { S: 'minecraft:string' })
  event.shapeless(Item.of('minecraft:string', 9), ['architects_palette:spool'])
  event.shaped('savage_and_ravage:conch_of_conjuring', [' WS', 'WNW', 'WW '], { W: 'architects_palette:withered_bone', N: 'minecraft:nautilus_shell', S: 'undead_unleashed:lost_soul' })
  event.shaped(Item.of('architects_palette:sunmetal_block', 12), ['PP', 'PP'], { P: 'architects_palette:sunmetal_brick' })
  event.shaped(Item.of('kubejs:raw_silver_bricks', 4), ['BB', 'BB'], { B: 'caverns_and_chasms:raw_silver_block' })
  event.shaped(Item.of('kubejs:raw_silver_brick_stairs', 4), ['B  ', 'BB ', 'BBB'], { B: 'kubejs:raw_silver_bricks' })
  event.shaped(Item.of('kubejs:raw_silver_brick_slab', 6), ['BBB'], { B: 'kubejs:raw_silver_bricks' })
  event.shaped(Item.of('kubejs:raw_zinc_bricks', 4), ['BB', 'BB'], { B: 'create:raw_zinc_block' })
  event.shaped(Item.of('kubejs:raw_zinc_brick_stairs', 4), ['B  ', 'BB ', 'BBB'], { B: 'kubejs:raw_zinc_bricks' })
  event.shaped(Item.of('kubejs:raw_zinc_brick_slab', 6), ['BBB'], { B: 'kubejs:raw_zinc_bricks' })
  event.shapeless(Item.of('caverns_and_chasms:raw_silver', 9), ['kubejs:raw_silver_bricks'])
  event.shapeless(Item.of('create:raw_zinc', 9), ['kubejs:raw_zinc_bricks'])
  event.shaped('minecraft:chainmail_helmet', ['GGG', 'G G'], { G: 'architects_palette:nether_brass_chain' })
  event.shaped('minecraft:chainmail_chestplate', ['G G', 'GGG', 'GGG'], { G: 'architects_palette:nether_brass_chain' })
  event.shaped('minecraft:chainmail_leggings', ['GGG', 'G G', 'G G'], { G: 'architects_palette:nether_brass_chain' })
  event.shaped('minecraft:chainmail_boots', ['G G', 'G G'], { G: 'architects_palette:nether_brass_chain' })
  event.shapeless('minecraft:grass_block', ['minecraft:dirt', 'minecraft:grass'])
  event.shapeless('minecraft:podzol', ['minecraft:grass_block', 'windswept:dry_moss_block'])
  event.shapeless('windswept:gelisol', ['minecraft:grass_block', 'windswept:gelisol_sprouts'])
  event.shapeless('atmospheric:crustose', ['minecraft:grass_block', 'atmospheric:golden_growths'])
  event.shapeless('atmospheric:crustose_log', ['atmospheric:aspen_log', 'atmospheric:golden_growths'])
  event.shapeless('atmospheric:crustose_wood', ['atmospheric:aspen_wood', 'atmospheric:golden_growths'])
  event.shaped(Item.of('quark:framed_glass', 4), ['GI', 'IG'], { G: 'minecraft:glass', I: 'minecraft:iron_ingot' })
  event.shaped('kubejs:bejeweled_apple_crate', ['AAA', 'AAA', 'AAA'], { A: 'minecraft:enchanted_golden_apple' })
  event.shapeless(Item.of('minecraft:enchanted_golden_apple', 9), ['kubejs:bejeweled_apple_crate'])
  event.shapeless('undead_unleashed:tome_of_reflection', ['undead_unleashed:lost_soul', 'minecraft:book', 'undead_unleashed:necrotic_dust', 'minecraft:ink_sac', 'quark:glow_shroom' ])
  event.shaped('supplementaries:goblet', ['N N', 'N N', ' N '], { N: 'caverns_and_chasms:silver_nugget' })
  event.shaped('supplementaries:doormat', ['HH'], { H: 'environmental:yak_hair' })
  event.shaped('mace_backport:mace', ['  S', ' R ', 'R  '], { R: 'kubejs:ice_rod', S: 'caverns_and_chasms:silver_block' })
  event.shaped('supplementaries:wind_vane', ['B', 'S'], { B: 'create:andesite_bars', S: 'kubejs:zinc_sheet' })
  event.shaped('irons_spellbooks:silver_ring', [' P ', 'PLP', ' P '], { L: 'minecraft:lapis_lazuli', P: 'undead_unleashed:grave_metal_ingot' })
  event.shaped('irons_spellbooks:cooldown_ring', ['JG ', 'G G', ' G '], { J: 'sullysmod:polished_jade_block', G: 'minecraft:gold_ingot' })
  event.shaped('irons_spellbooks:cast_time_ring', ['AC ', 'C C', ' C '], { A: 'caverns_and_chasms:amethyst_block', C: 'minecraft:copper_ingot' })
  event.shaped('irons_spellbooks:fireward_ring', ['HB ', 'BSB', ' B '], { H: 'heart_crystals:heart_crystal_shard', B: 'create:brass_sheet', S: 'minecraft:netherite_scrap' })

  event.shaped(Item.of('minecraft:bone_block', 3), ['BBB', 'BBB', 'BBB'], { B: 'minecraft:bone' })
  event.shapeless(Item.of('minecraft:bone', 3), ['minecraft:bone_block'])

  event.smelting('quark:midori_block', 'minecraft:moss_block')

  baking('quark:midori_block', 'minecraft:moss_block')
  baking('architects_palette:cracked_basalt_tiles', 'architects_palette:basalt_tiles')

  event.stonecutting('kubejs:grave_metal_plate_stairs', 'kubejs:grave_metal_plates')
  event.stonecutting(Item.of('kubejs:grave_metal_plate_slab', 2), 'kubejs:grave_metal_plates')
  event.stonecutting('kubejs:raw_silver_brick_stairs', 'kubejs:raw_silver_bricks')
  event.stonecutting(Item.of('kubejs:raw_silver_brick_slab', 2), 'kubejs:raw_silver_bricks')
  event.stonecutting('kubejs:raw_zinc_brick_stairs', 'kubejs:raw_zinc_bricks')
  event.stonecutting(Item.of('kubejs:raw_zinc_brick_slab', 2), 'kubejs:raw_zinc_bricks')
  event.stonecutting('architects_palette:dripstone_pillar', 'minecraft:dripstone_block')
  event.stonecutting('quark:raw_iron_bricks', 'minecraft:raw_iron_block')
  event.stonecutting('quark:raw_iron_bricks_stairs', 'minecraft:raw_iron_block')
  event.stonecutting(Item.of('quark:raw_iron_bricks_slab', 2), 'minecraft:raw_iron_block')
  event.stonecutting('quark:raw_copper_bricks', 'minecraft:raw_copper_block')
  event.stonecutting('quark:raw_copper_bricks_stairs', 'minecraft:raw_copper_block')
  event.stonecutting(Item.of('quark:raw_copper_bricks_slab', 2), 'minecraft:raw_copper_block')
  event.stonecutting('quark:raw_gold_bricks', 'minecraft:raw_gold_block')
  event.stonecutting('quark:raw_gold_bricks_stairs', 'minecraft:raw_gold_block')
  event.stonecutting(Item.of('quark:raw_gold_bricks_slab', 2), 'minecraft:raw_gold_block')
  event.stonecutting('kubejs:raw_silver_bricks', 'caverns_and_chasms:raw_silver_block')
  event.stonecutting('kubejs:raw_silver_brick_stairs', 'caverns_and_chasms:raw_silver_block')
  event.stonecutting(Item.of('kubejs:raw_silver_brick_slab', 2), 'caverns_and_chasms:raw_silver_block')
  event.stonecutting('kubejs:raw_zinc_bricks', 'create:raw_zinc_block')
  event.stonecutting('kubejs:raw_zinc_brick_stairs', 'create:raw_zinc_block')
  event.stonecutting(Item.of('kubejs:raw_zinc_brick_slab', 2), 'create:raw_zinc_block')

  event.smithing('artifacts:aqua_dashers', 'minecraft:leather_boots', 'cataclysm:coral_chunk')
  event.smithing('windswept:snow_boots', 'minecraft:leather_boots', 'caverns_and_chasms:silver_ingot')
  event.smithing('create:copper_diving_boots', 'metalworks:copper_boots', 'minecraft:deepslate')
  event.smithing('clash:greatblade', 'savage_and_ravage:cleaver_of_beheading', 'cataclysm:ignitium_ingot')

  event.recipes.create.pressing('kubejs:silver_sheet', 'caverns_and_chasms:silver_ingot')
  event.recipes.create.pressing('kubejs:zinc_sheet', 'create:zinc_ingot')
  event.recipes.create.pressing('minecraft:dirt_path', 'minecraft:grass_block')
  event.recipes.create.pressing('environmental:dirt_path', 'minecraft:dirt')
  event.recipes.create.pressing('windswept:gelisol_path', 'windswept:gelisol')

  event.recipes.create.emptying([Fluid.water(), 'windswept:wooden_bucket'], 'windswept:wooden_water_bucket')
  event.recipes.create.emptying([Fluid.of('minecraft:milk'), 'windswept:wooden_bucket'], 'windswept:wooden_milk_bucket')
  event.recipes.create.emptying([Fluid.water(), 'caverns_and_chasms:golden_bucket'], 'caverns_and_chasms:golden_water_bucket')
  event.recipes.create.emptying([Fluid.of('minecraft:milk'), 'caverns_and_chasms:golden_bucket'], 'caverns_and_chasms:golden_milk_bucket')
  event.recipes.create.emptying([Fluid.lava(), 'caverns_and_chasms:golden_bucket'], 'caverns_and_chasms:golden_lava_bucket')

  event.recipes.create.mixing(['minecraft:slime_ball'], [Fluid.of('minecraft:milk', 250), Item.of('minecraft:kelp', 2)])
  event.recipes.create.mixing(['minecraft:slime_ball'], [Item.of('atmospheric:aloe_leaves', 2)])
  event.recipes.create.mixing(['upgrade_aquatic:driftwood_log'], [Fluid.of('minecraft:water', 250), '#minecraft:logs'])
  event.recipes.create.mixing([Item.of('minecraft:coarse_dirt', 2)], ['minecraft:dirt', 'minecraft:gravel'])
  event.recipes.create.mixing([Item.of('caverns_and_chasms:rocky_dirt', 2)], ['minecraft:dirt', 'minecraft:cobblestone'])
  event.recipes.create.mixing([Item.of('architects_palette:coarse_snow', 2)], ['minecraft:snow_block', 'minecraft:gravel'])
  event.recipes.create.mixing([Item.of('minecraft:red_nether_bricks', 2)], ['minecraft:nether_bricks', 'minecraft:nether_wart_block'])
  event.recipes.create.mixing([Item.of('quark:blue_nether_bricks', 2)], ['minecraft:nether_bricks', 'minecraft:warped_wart_block'])
  event.recipes.create.mixing([Item.of('architects_palette:molten_nether_bricks', 2)], ['minecraft:nether_bricks', 'minecraft:magma_block'])
  event.recipes.create.mixing([Item.of('minecraft:tuff', 2)], ['minecraft:basalt', 'minecraft:cobblestone'])
  event.recipes.create.mixing([Item.of('windswept:shale', 2)], ['minecraft:blue_ice', 'minecraft:cobblestone'])
  event.recipes.create.mixing([Item.of('atmospheric:dolerite', 2)], ['#rrm:sandstone', 'minecraft:cobblestone'])
  event.recipes.create.mixing(['caverns_and_chasms:flooded_dripstone_shingles'], [Fluid.of('minecraft:water', 125), 'caverns_and_chasms:dripstone_shingles'])
  event.recipes.create.mixing(['berry_good:sweet_berry_mince'], ['minecraft:sweet_berries', 'minecraft:porkchop'])
  event.recipes.create.mixing(['create:blaze_cake'], [Fluid.of('minecraft:lava', 1000), Item.of('create:cinder_flour', 4), Item.of('create:wheat_flour', 2), '#forge:eggs']).heated()
  event.recipes.create.mixing(['abnormals_delight:pickerelweed_juice'], ['#rrm:pickerelweed', '#rrm:pickerelweed', 'minecraft:sugar', 'minecraft:glass_bottle'])
  event.recipes.create.mixing(['abnormals_delight:cherry_cream_soda'], [Fluid.of('minecraft:milk', 250), 'environmental:cherries', 'neapolitan:dried_vanilla_pods', 'minecraft:sugar', 'minecraft:glass_bottle'])
  event.recipes.create.mixing(['abnormals_delight:passion_aloe_nectar'], [Item.of('atmospheric:passion_fruit', 2), 'atmospheric:aloe_leaves', 'minecraft:glass_bottle'])
  event.recipes.create.mixing(['abnormals_delight:slabdish'], ['#forge:raw_fishes', 'environmental:dianthus', 'minecraft:bone_meal', '#abnormals_delight:slabdish_ingredients', '#abnormals_delight:slabdish_ingredients', 'minecraft:bowl'])
  event.recipes.create.mixing(['abnormals_delight:duck_noodles'], ['environmental:duck', 'farmersdelight:raw_pasta', 'minecraft:carrot', 'windswept:ginger_root', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['abnormals_delight:escargot'], [Fluid.of('minecraft:milk'), Item.of('autumnity:snail_goo', 2), 'farmersdelight:onion', 'autumnity:snail_shell_piece']).heated()
  event.recipes.create.mixing(['abnormals_delight:pike_with_beetroot'], ['#rrm:pickerelweed', 'upgrade_aquatic:pike', 'minecraft:bowl', Item.of('minecraft:beetroot', 2)]).heated()
  event.recipes.create.mixing(['abnormals_delight:perch_with_mushrooms'], ['upgrade_aquatic:perch', Item.of('minecraft:red_mushroom', 2), 'farmersdelight:rice', 'farmersdelight:tomato', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['windswept:ginger_tea'], [Fluid.of('minecraft:water', 250), Item.of('windswept:ginger_root', 4), 'minecraft:glass_bottle']).heated()
  event.recipes.create.mixing(['windswept:lavender_tea'], [Fluid.of('minecraft:water', 250), Item.of('windswept:lavender', 4), 'minecraft:glass_bottle']).heated()
  event.recipes.create.mixing(['farmersdelight:apple_cider'], [Item.of('minecraft:apple', 2), 'minecraft:sugar', 'minecraft:glass_bottle']).heated()
  event.recipes.create.mixing(['abnormals_delight:venison_with_bamboo_shoots'], ['environmental:venison', Item.of('minecraft:bamboo', 2), 'minecraft:beetroot', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['autumnity:foul_soup'], [Item.of('autumnity:foul_berries', 2), 'minecraft:spider_eye', 'farmersdelight:onion', 'minecraft:bowl'])
  event.recipes.create.mixing(['minecraft:beetroot_soup'], [Item.of('minecraft:beetroot', 4), 'minecraft:bowl'])
  event.recipes.create.mixing(['windswept:goat_stew'], ['windswept:goat', 'farmersdelight:rice', 'minecraft:potato', 'farmersdelight:tomato', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['incubation:scrambled_eggs'], [Fluid.of('minecraft:milk', 250), '#forge:eggs', '#forge:eggs', 'minecraft:bowl'])
  event.recipes.create.mixing(['minecraft:mushroom_stew'], ['minecraft:red_mushroom', 'minecraft:brown_mushroom', 'minecraft:bowl'])
  event.recipes.create.mixing(['farmersdelight:cooked_rice'], ['farmersdelight:rice', 'farmersdelight:rice', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['windswept:chestnut_soup'], [Item.of('windswept:chestnuts', 2), 'farmersdelight:onion', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['windswept:chestnut_risotto'], [Item.of('windswept:chestnuts', 3), 'farmersdelight:onion', 'farmersdelight:rice', 'minecraft:chicken', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:squid_ink_pasta'], ['#forge:raw_fishes', 'farmersdelight:raw_pasta', 'farmersdelight:tomato', 'minecraft:ink_sac', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['minecraft:rabbit_stew'], ['minecraft:red_mushroom', 'minecraft:potato', 'minecraft:rabbit', 'minecraft:carrot', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:bone_broth'], ['minecraft:bone', 'minecraft:bone', 'minecraft:brown_mushroom', 'minecraft:hanging_roots', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:beef_stew'], ['minecraft:beef', 'minecraft:carrot', 'minecraft:potato', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:mushroom_rice'], ['minecraft:red_mushroom', 'minecraft:brown_mushroom', 'farmersdelight:rice', 'minecraft:carrot', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:vegetable_noodles'], ['minecraft:brown_mushroom', 'minecraft:carrot', 'farmersdelight:raw_pasta', 'farmersdelight:cabbage', 'minecraft:potato', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:fried_rice'], ['minecraft:carrot', 'farmersdelight:rice', 'farmersdelight:onion', '#forge:eggs', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:dog_food'], ['#rrm:rotten_flesh', 'farmersdelight:rice', 'minecraft:bone_meal', '#farmersdelight:wolf_prey', 'minecraft:bowl'])
  event.recipes.create.mixing(['farmersdelight:ratatouille'], ['farmersdelight:tomato', 'farmersdelight:onion', 'minecraft:beetroot', 'minecraft:potato', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:pasta_with_mutton_chop'], ['minecraft:mutton', 'farmersdelight:tomato', 'farmersdelight:raw_pasta', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:pumpkin_soup'], [Fluid.of('minecraft:milk'), 'farmersdelight:pumpkin_slice', 'farmersdelight:pumpkin_slice', 'farmersdelight:cabbage', 'minecraft:porkchop', 'minecraft:bowl']).heated()
  event.recipes.create.mixing(['farmersdelight:fish_stew'], ['#forge:raw_fishes', 'farmersdelight:tomato', 'farmersdelight:onion', 'minecraft:bowl']).heated()
  event.recipes.create.mixing([Item.of('atmospheric:currant_muffin', 2)], [Item.of('atmospheric:currant', 3), 'create:wheat_flour', '#forge:eggs', 'minecraft:sugar']).heated()
  event.recipes.create.mixing(['autumnity:pancake'], [Fluid.of('minecraft:milk', 250), 'autumnity:syrup_bottle', Item.of('create:wheat_flour', 2), '#forge:eggs', 'minecraft:sugar']).heated()
  event.recipes.create.mixing(['windswept:christmas_pudding'], [Fluid.of('minecraft:milk'), 'windswept:ginger_root', 'windswept:holly_berries', 'windswept:roasted_chestnuts', 'create:wheat_flour', '#forge:eggs', 'minecraft:sugar']).heated()
  event.recipes.create.mixing(['atmospheric:yucca_gateau'], [Fluid.of('minecraft:milk'), Item.of('atmospheric:roasted_yucca_fruit', 2), Item.of('atmospheric:aloe_leaves', 2), Item.of('create:wheat_flour', 2), 'atmospheric:yucca_flower', 'minecraft:sugar']).heated()
  event.recipes.create.mixing([Item.of('atmospheric:orange_pudding', 2)], [Fluid.of('minecraft:milk'), Item.of('atmospheric:orange', 2), 'minecraft:sweet_berries', 'create:wheat_flour', '#forge:eggs'])
  event.recipes.create.mixing(['minecraft:netherite_ingot'], [Fluid.of('minecraft:lava'), Item.of('minecraft:netherite_scrap', 4), Item.of('minecraft:gold_ingot', 4)]).superheated()
  event.recipes.create.mixing(['caverns_and_chasms:necromium_ingot'], [Fluid.of('minecraft:lava'), Item.of('minecraft:netherite_scrap', 4), Item.of('caverns_and_chasms:silver_ingot', 4)]).superheated()
  event.recipes.create.mixing(['farmersdelight:melon_juice'], [Item.of('minecraft:melon_slice', 4), 'minecraft:sugar', 'minecraft:glass_bottle'])
  event.recipes.create.mixing(['windswept:wild_berry_juice'], [Item.of('windswept:wild_berries', 4), 'minecraft:sugar', 'minecraft:glass_bottle'])
  event.recipes.create.mixing(['berry_good:glowgurt'], [Fluid.of('minecraft:milk', 250), Item.of('minecraft:glow_berries', 2), 'minecraft:sugar', 'minecraft:bowl'])
  event.recipes.create.mixing(['atmospheric:passion_fruit_sorbet'], ['atmospheric:passion_fruit', 'windswept:icicles', 'minecraft:sugar', 'minecraft:bowl'])
  event.recipes.create.mixing(['atmospheric:orange_sorbet'], ['atmospheric:orange', 'windswept:icicles', 'minecraft:sugar', 'minecraft:bowl'])
  event.recipes.create.mixing(['neapolitan:vanilla_ice_cream'], [Fluid.of('minecraft:milk', 250), 'neapolitan:dried_vanilla_pods', 'windswept:icicles', 'minecraft:sugar', 'minecraft:bowl'])
  event.recipes.create.mixing(['neapolitan:strawberry_ice_cream'], [Fluid.of('minecraft:milk', 250), 'neapolitan:strawberries', 'windswept:icicles', 'minecraft:sugar', 'minecraft:bowl'])
  event.recipes.create.mixing(['neapolitan:banana_ice_cream'], [Fluid.of('minecraft:milk', 250), 'neapolitan:banana', 'windswept:icicles', 'minecraft:sugar', 'minecraft:bowl'])
  event.recipes.create.mixing(['neapolitan:vanilla_pudding'], ['neapolitan:dried_vanilla_pods', '#forge:eggs', 'minecraft:sugar', 'minecraft:bowl'])
  event.recipes.create.mixing(['neapolitan:vanilla_cake'], [Fluid.of('minecraft:milk'), Item.of('neapolitan:dried_vanilla_pods', 2), Item.of('create:wheat_flour', 2), Item.of('minecraft:sugar', 2), '#forge:eggs']).heated()
  event.recipes.create.mixing(['neapolitan:strawberry_cake'], [Fluid.of('minecraft:milk'), Item.of('neapolitan:strawberries', 2), Item.of('create:wheat_flour', 2), Item.of('minecraft:sugar', 2), '#forge:eggs']).heated()
  event.recipes.create.mixing(['neapolitan:banana_cake'], [Fluid.of('minecraft:milk'), Item.of('neapolitan:banana', 2), Item.of('create:wheat_flour', 2), Item.of('minecraft:sugar', 2), '#forge:eggs']).heated()
  event.recipes.create.mixing(['neapolitan:strawberry_banana_smoothie'], [Item.of('neapolitan:strawberries', 2), 'neapolitan:banana', 'minecraft:glass_bottle'])
  event.recipes.create.mixing(['sullysmod:cave_chum_bucket'], ['sullysmod:cooked_lanternfish', 'quark:glow_shroom', 'minecraft:bucket'])
  event.recipes.create.mixing(['minecraft:coal_ore'], ['minecraft:coal', 'minecraft:stone'])
  event.recipes.create.mixing(['minecraft:deepslate_coal_ore'], ['minecraft:coal', 'minecraft:deepslate'])
  event.recipes.create.mixing(['minecraft:iron_ore'], ['minecraft:raw_iron', 'minecraft:stone'])
  event.recipes.create.mixing(['minecraft:deepslate_iron_ore'], ['minecraft:raw_iron', 'minecraft:deepslate'])
  event.recipes.create.mixing(['minecraft:copper_ore'], ['minecraft:raw_copper', 'minecraft:stone'])
  event.recipes.create.mixing(['minecraft:deepslate_copper_ore'], ['minecraft:raw_copper', 'minecraft:deepslate'])
  event.recipes.create.mixing(['minecraft:gold_ore'], ['minecraft:raw_gold', 'minecraft:stone'])
  event.recipes.create.mixing(['minecraft:deepslate_gold_ore'], ['minecraft:raw_gold', 'minecraft:deepslate'])
  event.recipes.create.mixing(['minecraft:lapis_ore'], ['minecraft:lapis_lazuli', 'minecraft:stone'])
  event.recipes.create.mixing(['minecraft:deepslate_lapis_ore'], ['minecraft:lapis_lazuli', 'minecraft:deepslate'])
  event.recipes.create.mixing(['minecraft:diamond_ore'], ['minecraft:diamond', 'minecraft:stone'])
  event.recipes.create.mixing(['minecraft:deepslate_diamond_ore'], ['minecraft:diamond', 'minecraft:deepslate'])
  event.recipes.create.mixing(['sullysmod:jade_ore'], ['sullysmod:polished_jade', 'minecraft:stone'])
  event.recipes.create.mixing(['sullysmod:deepslate_jade_ore'], ['sullysmod:polished_jade', 'minecraft:deepslate'])
  event.recipes.create.mixing(['create:zinc_ore'], ['create:raw_zinc', 'minecraft:stone'])
  event.recipes.create.mixing(['create:deepslate_zinc_ore'], ['create:raw_zinc', 'minecraft:deepslate'])
  event.recipes.create.mixing(['caverns_and_chasms:silver_ore'], ['caverns_and_chasms:raw_silver', 'minecraft:stone'])
  event.recipes.create.mixing(['caverns_and_chasms:deepslate_silver_ore'], ['caverns_and_chasms:raw_silver', 'minecraft:deepslate'])
  event.recipes.create.mixing(['caverns_and_chasms:spinel_ore'], ['caverns_and_chasms:spinel', 'minecraft:stone'])
  event.recipes.create.mixing(['caverns_and_chasms:deepslate_spinel_ore'], ['caverns_and_chasms:spinel', 'minecraft:deepslate'])
  event.recipes.create.mixing(['minecraft:nether_gold_ore'], ['minecraft:raw_gold', 'minecraft:netherrack'])
  event.recipes.create.mixing(['minecraft:nether_quartz_ore'], ['minecraft:charcoal', 'minecraft:netherrack'])
  event.recipes.create.mixing(['minecraft:gilded_blackstone'], ['minecraft:raw_gold', 'minecraft:blackstone'])
  event.recipes.create.mixing(['caverns_and_chasms:soul_silver_ore'], ['caverns_and_chasms:raw_silver', '#minecraft:soul_fire_base_blocks'])

  event.recipes.create.crushing(['create:wheat_flour', Item.of('create:wheat_flour').withChance(0.5)], 'minecraft:wheat')
  event.recipes.create.crushing(['minecraft:sugar', Item.of('minecraft:sugar').withChance(0.5)], 'minecraft:sugar_cane')
  event.recipes.create.crushing([Item.of('caverns_and_chasms:silver_ingot', 2), Item.of('minecraft:leather', 2).withChance(0.5), Item.of('caverns_and_chasms:silver_ingot', 2).withChance(0.5), Item.of('minecraft:string', 2).withChance(0.25), Item.of('caverns_and_chasms:silver_nugget', 8).withChance(0.25)], 'caverns_and_chasms:silver_horse_armor')
  event.recipes.create.crushing([Item.of('minecraft:copper_ingot', 2), Item.of('minecraft:leather').withChance(0.5), Item.of('minecraft:copper_ingot').withChance(0.5), Item.of('minecraft:string', 2).withChance(0.25), Item.of('caverns_and_chasms:copper_nugget', 4).withChance(0.25)], 'metalworks:copper_horse_armor')
  event.recipes.create.crushing([Item.of('caverns_and_chasms:necromium_nugget', 2), Item.of('minecraft:leather', 2).withChance(0.5), Item.of('minecraft:string', 2).withChance(0.25), Item.of('caverns_and_chasms:necromium_nugget', 2).withChance(0.5)], 'caverns_and_chasms:necromium_horse_armor')
  event.recipes.create.crushing([Item.of('caverns_and_chasms:netherite_nugget', 2), Item.of('minecraft:leather', 2).withChance(0.5), Item.of('minecraft:string', 2).withChance(0.25), Item.of('caverns_and_chasms:netherite_nugget', 2).withChance(0.5)], 'caverns_and_chasms:netherite_horse_armor')
  event.recipes.create.crushing([Item.of('minecraft:leather', 2), Item.of('minecraft:leather').withChance(0.5), Item.of('minecraft:string', 2).withChance(0.5)], 'minecraft:saddle')
  event.recipes.create.crushing([Item.of('minecraft:flint').withChance(0.1), Item.of('create:zinc_nugget').withChance(0.2), Item.of('caverns_and_chasms:copper_nugget').withChance(0.2), Item.of('minecraft:iron_nugget').withChance(0.15), Item.of('minecraft:gold_nugget').withChance(0.1), Item.of('caverns_and_chasms:silver_nugget').withChance(0.1)], 'minecraft:tuff')
  event.recipes.create.crushing([Item.of('minecraft:sand', 2), Item.of('minecraft:sand', 2).withChance(0.5)], 'minecraft:sandstone')
  event.recipes.create.crushing([Item.of('minecraft:red_sand', 2), Item.of('minecraft:red_sand', 2).withChance(0.5)], 'minecraft:red_sandstone')
  event.recipes.create.crushing([Item.of('atmospheric:red_arid_sand', 2), Item.of('atmospheric:red_arid_sand', 2).withChance(0.5), Item.of('minecraft:gold_nugget').withChance(0.05)], 'atmospheric:red_arid_sandstone')
  event.recipes.create.crushing([Item.of('atmospheric:arid_sand', 2), Item.of('atmospheric:arid_sand', 2).withChance(0.5), Item.of('minecraft:gold_nugget').withChance(0.05)], 'atmospheric:arid_sandstone')
  event.recipes.create.crushing([Item.of('minecraft:flint').withChance(0.25), Item.of('minecraft:ice').withChance(0.33), Item.of('minecraft:packed_ice').withChance(0.33), Item.of('minecraft:blue_ice').withChance(0.33), Item.of('caverns_and_chasms:silver_nugget').withChance(0.05)], 'windswept:shale')
  event.recipes.create.crushing([Item.of('minecraft:gunpowder').withChance(0.1), Item.of('create:brass_nugget').withChance(0.05), Item.of('minecraft:glowstone_dust').withChance(0.1), Item.of('create:cinder_flour').withChance(0.1)], 'undead_unleashed:charstone_shard')
  event.recipes.create.crushing([Item.of('create:zinc_nugget', 2), Item.of('caverns_and_chasms:silver_nugget', 2).withChance(0.5)], 'undead_unleashed:grave_metal_scrap')
  event.recipes.create.crushing([Item.of('minecraft:iron_nugget', 9).withChance(0.5)], '#rrm:iron_equipment')
  event.recipes.create.crushing([Item.of('minecraft:gold_nugget', 9).withChance(0.5)], '#rrm:golden_equipment')
  event.recipes.create.crushing([Item.of('caverns_and_chasms:copper_nugget', 9).withChance(0.5)], '#rrm:copper_equipment')
  event.recipes.create.crushing([Item.of('caverns_and_chasms:silver_nugget', 9).withChance(0.5)], '#rrm:silver_equipment')
  event.recipes.create.crushing([Item.of('create:zinc_nugget', 9).withChance(0.5)], '#rrm:zinc_equipment')
  event.recipes.create.crushing([Item.of('create:brass_nugget', 9).withChance(0.5)], '#rrm:brass_equipment')
  event.recipes.create.crushing([Item.of('caverns_and_chasms:netherite_nugget', 9).withChance(0.5)], '#rrm:netherite_equipment')
  event.recipes.create.crushing([Item.of('caverns_and_chasms:necromium_nugget', 9).withChance(0.5)], '#rrm:necromium_equipment')

})

