ServerEvents.recipes(event => {
  // remove recipes
  event.remove({ type: 'create:sandpaper_polishing' });
  event.remove({ type: 'create:milling' });
  event.remove({ type: 'create:mechanical_crafting' });
  event.remove({ type: 'create:haunting' });
  event.remove({ type: 'create:compacting' });
  event.remove({ type: 'create:filling' });
  event.remove({ type: 'create:cutting' });
  event.remove({ type: 'create:deploying' });
  event.remove({ type: 'create:splashing' });
  event.remove({ type: 'farmersdelight:cutting' });

  event.remove({ output: 'buzzier_bees:crystallized_honey_block' })
  event.remove({ output: 'buzzier_bees:honey_lamp' })
  event.remove({ output: 'caverns_and_chasms:lava_lamp' })
  event.remove({ output: 'minecraft:chain' })
  event.remove({ output: 'minecraft:calcite' })
  //event.remove({ output: 'architects_palette:nether_brass_chain' })
  event.remove({ output: 'create:brass_hand' })
  event.remove({ output: 'caverns_and_chasms:sanguine_plating' })
  event.remove({ output: 'caverns_and_chasms:tuning_fork' })
  event.remove({ output: 'create:andesite_alloy' })
  event.remove({ output: 'create:track' })
  event.remove({ output: 'create:railway_casing' })
  event.remove({ output: 'create:brass_sheet' })
  event.remove({ output: 'create:sturdy_sheet' })
  event.remove({ output: 'create:experience_nugget' })
  event.remove({ output: 'create:crushed_raw_zinc' })
  event.remove({ output: 'create:crushed_raw_iron' })
  event.remove({ output: 'create:crushed_raw_gold' })
  event.remove({ output: 'create:crushed_raw_copper' })
  event.remove({ output: 'create:bar_of_chocolate' })
  event.remove({ output: 'create:chocolate_glazed_berries' })
  event.remove({ output: 'minecraft:popped_chorus_fruit' })
  event.remove({ id: 'create:crafting/materials/copper_ingot' })
  event.remove({ id: 'create:crafting/appliances/slime_ball' })
  event.remove({ output: 'minecraft:bread' })
  event.remove({ output: 'create:dough' })
  event.remove({ output: 'create:copper_casing' })
  event.remove({ id: 'create:crushing/amethyst_cluster' })
  event.remove({ id: 'create:crushing/amethyst_block' })
  event.remove({ id: 'create:crushing/glowstone' })
  event.remove({ id: 'create:crushing/blaze_rod' })
  event.remove({ id: 'create:crushing/nether_wart_block' })
  event.remove({ id: 'create:mixing/tea' })
  event.remove({ id: 'create:mixing/chocolate' })
  event.remove({ id: 'create:mixing/chocolate_melting' })
  event.remove({ id: 'create:mixing/mud_by_mixing' })
  event.remove({ id: 'create:mixing/honey' })
  event.remove({ id: 'create:emptying/honey_bottle' })
  event.remove({ id: 'create:pressing/path' })
  event.remove({ output: 'minecraft:quartz', type: 'create:crushing' });
  event.remove({ output: 'minecraft:daylight_detector' })
  event.remove({ output: 'create:andesite_bars' })
  event.remove({ output: 'create:brass_bars' })
  event.remove({ output: 'minecraft:glass_pane', tyoe: 'minecraft:smelting' })
  event.remove({ id: 'create:smelting/glass_from_tiled_glass' })
  event.remove({ id: 'create:smelting/glass_from_framed_glass' })
  event.remove({ id: 'create:smelting/glass_from_horizontal_framed_glass' })
  event.remove({ id: 'create:smelting/glass_from_vertical_framed_glass' })
  event.remove({ output: 'minecraft:nether_wart_block' })
  event.remove({ output: 'minecraft:powered_rail' })
  event.remove({ id: 'environmental:mud_ball' })
  event.remove({ output: 'minecraft:soul_torch' })
  event.remove({ output: 'caverns_and_chasms:cupric_torch' })
  event.remove({ output: 'minecraft:pumpkin_pie' })
  event.remove({ id: 'farmersdelight:milk_bucket_from_bottles' })
  event.remove({ id: 'farmersdelight:pumpkin_from_slices' })
  event.remove({ id: 'minecraft:pumpkin_seeds' })
  event.remove({ output: 'clash:spear' })
  event.remove({ output: 'clash:rod_of_gales' })
  event.remove({ output: 'farmersdelight:organic_compost' })

  // edit recipes
  event.replaceOutput({ output: 'minecraft:quartz' }, 'minecraft:quartz', 'minecraft:charcoal')
  event.replaceInput({ input: 'minecraft:torch' }, 'minecraft:torch', 'realistictorches:lit_torch')
  //event.replaceInput({ input: 'irons_spellbooks:arcane_essence' }, 'irons_spellbooks:arcane_essence', 'minecraft:lapis_lazuli')
  event.replaceInput({ input: 'create:brass_sheet' }, 'create:brass_sheet', 'create:brass_ingot')
  event.replaceInput({ input: 'create:andesite_alloy' }, 'create:andesite_alloy', 'create:zinc_ingot')
  event.replaceInput({ input: 'minecraft:redstone' }, 'minecraft:redstone', 'kubejs:copper_wire')
  event.replaceInput({ input: 'create:electron_tube' }, 'create:electron_tube', 'kubejs:power_coil')
  event.replaceInput({ input: 'minecraft:quartz' }, 'minecraft:quartz', 'minecraft:amethyst_shard')
  event.replaceInput({ output: 'create:mechanical_arm' }, 'create:zinc_ingot', 'create:brass_hand')
  event.replaceInput({ output: 'minecraft:bucket' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'create:weighted_ejector' }, 'create:golden_sheet', 'kubejs:silver_sheet')
  event.replaceInput({ output: 'caverns_and_chasms:toolbox' }, 'minecraft:copper_ingot', 'caverns_and_chasms:copper_nugget')
  event.replaceInput({ output: 'caverns_and_chasms:toolbox' }, 'minecraft:copper_block', 'create:copper_sheet')
  event.replaceInput({ output: 'create:goggles' }, '#forge:glass', 'minecraft:amethyst_shard')
  event.replaceInput({ output: 'create:item_vault' }, 'create:iron_sheet', 'kubejs:silver_sheet')
  event.replaceInput({ output: 'create:super_glue' }, 'minecraft:iron_nugget', 'caverns_and_chasms:copper_nugget')
  event.replaceInput({ output: 'create:super_glue' }, 'create:iron_sheet', 'create:copper_sheet')
  event.replaceInput({ output: 'create:redstone_contact' }, 'create:iron_sheet', 'create:copper_sheet')
  event.replaceInput({ output: 'autumnity:pumpkin_bread' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'minecraft:tripwire_hook' }, 'minecraft:iron_ingot', 'create:zinc_ingot')
  event.replaceInput({ output: 'minecraft:lever' }, 'minecraft:cobblestone', 'create:zinc_ingot')
  event.replaceInput({ output: 'minecraft:smithing_table' }, 'minecraft:iron_ingot', 'caverns_and_chasms:silver_ingot')
  event.replaceInput({ output: 'minecraft:clock' }, 'minecraft:gold_ingot', 'create:golden_sheet')
  event.replaceInput({ output: 'minecraft:compass' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'caverns_and_chasms:barometer' }, 'minecraft:copper_ingot', 'create:copper_sheet')
  event.replaceInput({ output: 'caverns_and_chasms:depth_gauge' }, 'caverns_and_chasms:silver_ingot', 'kubejs:silver_sheet')
  event.replaceInput({ output: 'create:basin' }, 'create:zinc_ingot', 'minecraft:iron_ingot')
  event.replaceInput({ output: 'minecraft:minecart' }, 'minecraft:iron_ingot', 'create:zinc_ingot')
  event.replaceInput({ output: 'minecraft:redstone_lamp' }, 'kubejs:copper_wire', 'minecraft:glowstone_dust')
  event.replaceInput({ output: 'minecraft:redstone_lamp' }, 'minecraft:glowstone', 'kubejs:copper_wire')
  event.replaceInput({ output: 'minecraft:rail' }, 'minecraft:iron_nugget', 'create:zinc_nugget')
  event.replaceInput({ output: 'minecraft:activator_rail' }, 'minecraft:iron_nugget', 'caverns_and_chasms:copper_nugget')
  event.replaceInput({ output: 'minecraft:activator_rail' }, 'minecraft:redstone_torch', 'kubejs:power_coil')
  event.replaceInput({ output: 'minecraft:brewing_stand' }, 'minecraft:blaze_rod', 'upgrade_aquatic:prismarine_rod')
  event.replaceInput({ output: 'minecraft:brewing_stand' }, 'caverns_and_chasms:silver_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'minecraft:red_nether_bricks' }, 'minecraft:nether_wart', 'minecraft:magma_cream')
  event.replaceInput({ output: 'minecraft:note_block' }, 'kubejs:copper_wire', 'create:brass_ingot')
  event.replaceInput({ output: 'create:redstone_contact' }, 'kubejs:copper_wire', 'kubejs:power_coil')
  event.replaceInput({ output: 'create:stockpile_switch' }, 'minecraft:comparator', 'create:portable_storage_interface')
  event.replaceInput({ output: 'minecraft:heavy_weighted_pressure_plate' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'minecraft:light_weighted_pressure_plate' }, 'minecraft:gold_ingot', 'create:golden_sheet')
  event.replaceInput({ output: 'caverns_and_chasms:medium_weighted_pressure_plate' }, 'caverns_and_chasms:silver_ingot', 'kubejs:silver_sheet')
  event.replaceInput({ output: 'create:sticker' }, 'kubejs:copper_wire', 'kubejs:power_coil')
  event.replaceInput({ output: 'atmospheric:passion_fruit_sorbet' }, 'minecraft:ice', 'windswept:icicles')
  event.replaceInput({ output: 'atmospheric:orange_sorbet' }, 'minecraft:ice', 'windswept:icicles')
  event.replaceInput({ output: 'windswept:mutton_pie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'windswept:lavender_scones' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'windswept:wild_berry_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'windswept:gingerbread_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  //event.replaceInput({ output: 'irons_spellbooks:mana_ring' }, 'irons_spellbooks:arcane_ingot', 'caverns_and_chasms:silver_ingot')
  event.replaceInput({ output: 'farmersdelight:honey_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'farmersdelight:sweet_berry_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'abnormals_delight:cherry_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'abnormals_delight:maple_cookie' }, 'minecraft:wheat', 'create:wheat_flour')
  event.replaceInput({ output: 'farmersdelight:skillet' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'create:rope_pulley' }, '#minecraft:wool', 'farmersdelight:rope')
  event.replaceInput({ output: 'minecraft:stonecutter' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'woodworks:sawmill' }, 'minecraft:iron_ingot', 'create:iron_sheet')
  event.replaceInput({ output: 'minecraft:sea_lantern' }, 'minecraft:prismarine_shard', 'upgrade_aquatic:prismarine_rod')
  event.replaceInput({ output: 'windswept:frost_arrow' }, 'minecraft:stick', 'kubejs:ice_rod')
  event.replaceInput({ output: 'windswept:frost_arrow' }, 'windswept:icicles', 'minecraft:feather')
  event.replaceInput({ output: 'heart_crystals:heart_lantern' }, 'minecraft:iron_nugget', 'caverns_and_chasms:silver_nugget')
  event.replaceInput({ output: 'create:filter' }, '#minecraft:wool', 'farmersdelight:canvas')
  event.replaceInput({ output: 'create:attribute_filter' }, '#minecraft:wool', 'farmersdelight:canvas')

  // add recipes
  event.shapeless('minecraft:bread', ['create:wheat_flour', 'create:wheat_flour', 'create:wheat_flour'])
  event.shapeless('minecraft:slime_ball', ['autumnity:snail_goo', 'minecraft:lime_dye'])
  event.shapeless(Item.of('buzzier_bees:honey_lamp', 2), ['minecraft:blaze_rod', 'minecraft:honey_bottle', 'create:golden_sheet'])
  event.shaped(Item.of('caverns_and_chasms:lava_lamp', 2), ['S', 'L', 'S'], { S: 'create:golden_sheet', L: '#forge:buckets/lava' })
  event.shaped('minecraft:chain', ['N', 'N', 'N'], { N: 'minecraft:iron_nugget' })
  //event.shaped('architects_palette:nether_brass_chain', ['N', 'N', 'N'], { N: 'create:brass_nugget' })
  event.shaped('create:brass_hand', [' B ', 'BBB', ' S '], { B: 'create:brass_ingot', S: 'kubejs:silver_sheet' })
  event.shapeless('caverns_and_chasms:sanguine_plating', ['kubejs:silver_sheet', '#rrm:rotten_flesh', 'heart_crystals:heart_crystal_shard'])
  event.shaped('create:crushing_wheel', ['III', 'ICI', 'III'], { I: 'minecraft:iron_ingot', C: 'create:large_cogwheel' })
  event.shaped('caverns_and_chasms:tuning_fork', [' S ', ' IS', 'I  '], { S: 'create:copper_sheet', I: 'minecraft:copper_ingot' })
  event.shaped('kubejs:silver_feather', ['NNN', 'NFN', 'NNN'], { N: 'caverns_and_chasms:silver_nugget', F: 'minecraft:feather' })
  event.shaped(Item.of('kubejs:copper_wire', 2), ['CIC'], { C: 'caverns_and_chasms:copper_nugget', I: 'minecraft:copper_ingot' })
  event.shaped('minecraft:elytra', ['F F', 'FFF', 'F F'], { F: 'kubejs:torn_elytra_fragment' })
  event.shapeless('kubejs:power_coil', ['kubejs:copper_wire', 'minecraft:blaze_powder'])
  event.shaped('minecraft:daylight_detector', ['GG', 'SS'], { G: 'minecraft:glass', S: 'create:copper_sheet' })
  event.shaped(Item.of('create:andesite_bars', 16), ['III', 'III'], { I: 'create:zinc_ingot' })
  event.shaped(Item.of('create:brass_bars', 16), ['III', 'III'], { I: 'create:brass_ingot' })
  event.shapeless('minecraft:crying_obsidian', ['minecraft:obsidian', 'minecraft:amethyst_shard'])
  event.shaped(Item.of('minecraft:powered_rail', 3), ['NSN', 'NCN', 'NSN'], { N: 'minecraft:gold_nugget', S: 'minecraft:stick', C: 'kubejs:power_coil' })
  event.shapeless('environmental:lumberer_banner_pattern', ['minecraft:paper', 'windswept:pinecone'])
  event.shapeless('minecraft:soul_torch', ['realistictorches:unlit_torch', 'realistictorches:matchbox', '#minecraft:soul_fire_base_blocks'])
  event.shapeless('caverns_and_chasms:cupric_torch', ['realistictorches:unlit_torch', 'realistictorches:matchbox', '#caverns_and_chasms:cupric_fire_base_blocks'])
  event.shapeless('minecraft:flint', ['minecraft:gravel'])
  event.shapeless(Item.of('farmersdelight:raw_pasta', 2), ['#forge:eggs', 'create:wheat_flour', 'create:wheat_flour'])
  event.shapeless('minecraft:pumpkin_pie', ['farmersdelight:pumpkin_slice', 'farmersdelight:pumpkin_slice', 'create:wheat_flour', 'minecraft:sugar', '#forge:eggs'])
  event.shaped('minecraft:pumpkin', ['SSS', 'SSS', 'SSS'], { S: 'farmersdelight:pumpkin_slice' })
  event.shaped('otherworldly_accessories:totem_of_regeneration', ['PPP', 'PHP', ' P '], { P: 'windswept:pinecone', H: 'heart_crystals:heart_crystal' })
  event.shapeless('upgrade_aquatic:pink_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:pink_dye'])
  event.shapeless('upgrade_aquatic:purple_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:purple_dye'])
  event.shapeless('upgrade_aquatic:blue_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:light_blue_dye'])
  event.shapeless('upgrade_aquatic:green_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:lime_dye'])
  event.shapeless('upgrade_aquatic:yellow_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:yellow_dye'])
  event.shapeless('upgrade_aquatic:orange_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:orange_dye'])
  event.shapeless('upgrade_aquatic:red_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:red_dye'])
  event.shapeless('upgrade_aquatic:white_jelly_torch', ['upgrade_aquatic:prismarine_rod', 'minecraft:glow_ink_sac', 'minecraft:white_dye'])
  event.shaped(Item.of('endermanoverhaul:icy_pearl', 2), [' I ', 'IPI', ' I '], { P: 'minecraft:ender_pearl', I: 'windswept:icicles' })
  event.shaped('kubejs:ice_rod', [' I', 'I '], { I: 'windswept:icicles' })

  event.recipes.create.pressing('kubejs:silver_sheet', 'caverns_and_chasms:silver_ingot')
  event.recipes.create.pressing('minecraft:dirt_path', 'minecraft:grass_block')
  event.recipes.create.pressing('environmental:dirt_path', 'minecraft:dirt')
  event.recipes.create.pressing('windswept:gelisol_path', 'windswept:gelisol')

  event.recipes.create.mixing(['minecraft:slime_ball'], [Fluid.of('minecraft:milk', 250), Item.of('minecraft:kelp', 2)])
  event.recipes.create.mixing(['create:blaze_cake'], [Fluid.of('minecraft:lava', 1000), Item.of('create:cinder_flour', 4), Item.of('create:wheat_flour', 2), '#forge:eggs']).heated()

  event.recipes.create.crushing(['create:wheat_flour', Item.of('create:wheat_flour').withChance(0.5)], 'minecraft:wheat')
})

