ServerEvents.tags('item', event => {
  event.removeAll('caverns_and_chasms:experience_boost_items')
  event.removeAll('curios:head')
  event.removeAll('curios:back')
  event.removeAll('curios:charm')
  event.removeAll('curios:necklace')
  event.removeAll('curios:belt')
  event.removeAll('curios:feet')
  event.removeAll('curios:hands')
  event.removeAll('curios:ring')
  event.removeAll('curios:spellbook')
  event.removeAll('caverns_and_chasms:cupric_fire_base_blocks')
  event.removeAll('supplementaries:ropes')
  event.removeAll('endergetic:ender_fire_base_blocks')

  event.add('curios:curio', 'create:goggles', 'minecraft:elytra', 'minecraft:totem_of_undying', 'artifacts:cross_necklace', 'artifacts:shock_pendant', 'artifacts:flame_pendant', 'artifacts:cloud_in_a_bottle', 'artifacts:obsidian_skull', 'artifacts:antidote_vessel', 'artifacts:fire_gauntlet', 'artifacts:aqua_dashers', 'undead_unleashed:tome_of_reflection', 'cataclysm:sandstorm_in_a_bottle', 'cataclysm:sticky_gloves', 'quark:backpack', 'irons_spellbooks:mana_ring', 'irons_spellbooks:silver_ring', 'irons_spellbooks:cooldown_ring', 'irons_spellbooks:cast_time_ring', 'irons_spellbooks:fireward_ring', 'irons_spellbooks:frostward_ring', 'irons_spellbooks:poisonward_ring', 'irons_spellbooks:heavy_chain_necklace', 'irons_spellbooks:concentration_amulet', 'irons_spellbooks:amethyst_resonance_charm')
  event.add('caverns_and_chasms:cupric_fire_base_blocks', 'minecraft:copper_ingot')
  event.add('rrm:rotten_flesh', 'minecraft:rotten_flesh', 'windswept:frozen_flesh')
  event.add('rrm:pickerelweed', 'upgrade_aquatic:blue_pickerelweed', 'upgrade_aquatic:purple_pickerelweed')
  event.add('rrm:sandstone', 'minecraft:sandstone', 'minecraft:red_sandstone', 'atmospheric:arid_sandstone', 'atmospheric:red_arid_sandstone')
  event.add('caverns_and_chasms:additional_toolbox_tools', 'create:wrench', '#curios:curio', 'artifacts:umbrella');
  event.add('forge:berries', 'autumnity:foul_berries', 'upgrade_aqutic:mulberry', 'atmospheric:currant', 'neapolitan:strawberries', 'neapolitan:white_strawberries')
  event.add('supplementaries:ropes', 'farmersdelight:rope')
  event.add('caverns_and_chasms:slowness_inflicting_items', 'undead_unleashed:reaping_scythe')
  event.add('caverns_and_chasms:magic_damage_items', 'undead_unleashed:moonlight_greatsword')
  event.add('rrm:iron_equipment', 'minecraft:iron_sword', 'minecraft:iron_pickaxe', 'minecraft:iron_shovel', 'minecraft:iron_axe', 'minecraft:iron_hoe', 'farmersdelight:iron_knife', 'minecraft:iron_helmet', 'minecraft:iron_chestplate', 'minecraft:iron_leggings', 'minecraft:iron_boots', 'minecraft:compass', 'otherworldly_accessories:broken_shackle')
  event.add('rrm:copper_equipment', 'metalworks:copper_sword', 'metalworks:copper_pickaxe', 'metalworks:copper_shovel', 'metalworks:copper_axe', 'metalworks:copper_hoe', 'metalworks:copper_knife', 'metalworks:copper_helmet', 'metalworks:copper_chestplate', 'metalworks:copper_leggings', 'metalworks:copper_boots', 'caverns_and_chasms:tuning_fork', 'caverns_and_chasms:barometer')
  event.add('rrm:golden_equipment', 'minecraft:golden_sword', 'minecraft:golden_pickaxe', 'minecraft:golden_shovel', 'minecraft:golden_axe', 'minecraft:golden_hoe', 'farmersdelight:golden_knife', 'minecraft:golden_helmet', 'minecraft:golden_chestplate', 'minecraft:golden_leggings', 'minecraft:golden_boots', 'minecraft:clock')
  event.add('rrm:silver_equipment', 'caverns_and_chasms:silver_sword', 'caverns_and_chasms:silver_pickaxe', 'caverns_and_chasms:silver_shovel', 'caverns_and_chasms:silver_axe', 'caverns_and_chasms:silver_hoe', 'abnormals_delight:silver_knife', 'caverns_and_chasms:silver_helmet', 'caverns_and_chasms:silver_chestplate', 'caverns_and_chasms:silver_leggings', 'caverns_and_chasms:silver_boots', 'caverns_and_chasms:depth_gauge')
  event.add('rrm:brass_equipment', 'minecraft:chainmail_helmet', 'minecraft:chainmail_chestplate', 'minecraft:chainmail_leggings', 'minecraft:chainmail_boots', 'create:wrench', 'create:goggles', 'otherworldly_accessories:battle_horseshoe')
  event.add('rrm:zinc_equipment', 'minecraft:shears', 'quark:trowel')
  event.add('rrm:netherite_equipment', 'minecraft:netherite_sword', 'savage_and_ravage:cleaver_of_beheading', 'minecraft:netherite_pickaxe', 'minecraft:netherite_shovel', 'minecraft:netherite_axe', 'minecraft:netherite_hoe', 'farmersdelight:netherite_knife', 'minecraft:netherite_helmet', 'minecraft:netherite_chestplate', 'minecraft:netherite_leggings', 'minecraft:netherite_boots')
  event.add('rrm:necromium_equipment', 'caverns_and_chasms:necromium_sword', 'caverns_and_chasms:necromium_pickaxe', 'caverns_and_chasms:necromium_shovel', 'caverns_and_chasms:necromium_axe', 'caverns_and_chasms:necromium_hoe', 'abnormals_delight:necromium_knife', 'caverns_and_chasms:necromium_helmet', 'caverns_and_chasms:necromium_chestplate', 'caverns_and_chasms:necromium_leggings', 'caverns_and_chasms:necromium_boots')
  event.add('endergetic:ender_fire_base_blocks', 'minecraft:amethyst_block')
  event.add('alexsmobs:bald_eagle_tameables', '#forge:raw_fishes')
  event.add('naturalist:giraffe_food_items', 'atmospheric:orange', 'atmospheric:blood_orange')

  event.remove('forge:cooked_eggs', 'farmersdelight:fried_egg')
  event.remove('environmental:spawns_on_muddy_pig', 'minecraft:blue_orchid', 'minecraft:dandelion', 'minecraft:poppy')
  event.remove('forge:crops/cabbage', 'farmersdelight:cabbage_leaf')
  event.remove('forge:cooked_mutton', 'farmersdelight:cooked_mutton_chops')
  event.remove('forge:cooked_chicken', 'farmersdelight:cooked_chicken_cuts')
  event.remove('forge:cooked_beef', 'farmersdelight:beef_patty')
  event.remove('forge:cooked_fishes/salmon', 'farmersdelight:cooked_salmon_slice')
  event.remove('forge:cooked_venison', 'abnormals_delight:cooked_venison_shanks')
  event.remove('forge:cooked_duck', 'abnormals_delight:cooked_duck_fillet')
  event.remove('forge:stripped_logs', 'minecraft:stripped_jungle_log', 'minecraft:stripped_acacia_log', 'minecraft:stripped_mangrove_log', 'architects_palette:stripped_twisted_log', 'quark:stripped_azalea_log', 'quark:stripped_blossom_log')
  event.remove('forge:stripped_wood', 'minecraft:stripped_jungle_wood', 'minecraft:stripped_acacia_wood', 'minecraft:stripped_mangrove_wood', 'architects_palette:stripped_twisted_wood', 'quark:stripped_azalea_wood', 'quark:stripped_blossom_wood')
  event.add('forge:stripped_logs', 'windswept:stripped_pine_log', 'windswept:stripped_holly_log', 'windswept:stripped_chestnut_log', 'caverns_and_chasms:stripped_azalea_log', 'upgrade_aquatic:stripped_driftwood_log', 'upgrade_aquatic:stripped_river_log', 'autumnity:stripped_maple_log', 'atmospheric:stripped_laurel_log')
  event.add('forge:stripped_wood', 'windswept:stripped_pine_wood', 'windswept:stripped_holly_wood', 'windswept:stripped_chestnut_wood', 'caverns_and_chasms:stripped_azalea_wood', 'upgrade_aquatic:stripped_driftwood', 'upgrade_aquatic:stripped_river_wood', 'autumnity:stripped_maple_wood', 'atmospheric:stripped_laurel_wood')
})

ServerEvents.tags('block', event => {
  event.removeAll('architects_palette:green_fire_supporting')
  event.removeAll('endergetic:ender_fire_base_blocks')

  event.add('auditory:leaf_sounds', '#minecraft:leaves', '#woodworks:leaf_piles', '#minecraft:saplings', 'environmental:hanging_willow_leaves', 'environmental:pink_hanging_wisteria_leaves', 'environmental:blue_hanging_wisteria_leaves', 'environmental:purple_hanging_wisteria_leaves', 'environmental:white_hanging_wisteria_leaves', 'atmospheric:passion_vine_bundle')
  event.add('auditory:string_sounds', 'atmospheric:grimweb', 'quark:glow_lichen_growth', 'incubation:hay_nest', 'incubation:twig_nest', 'vanillapluscompat:hay_emu_nest', 'vanillapluscompat:twig_emu_nest', 'incubation:hay_chicken_nest', 'incubation:twig_chicken_nest', 'incubation:hay_turkey_nest', 'incubation:twig_turkey_nest', 'incubation:hay_duck_nest', 'incubation:twig_duck_nest')
  event.add('auditory:clay_brick_sounds', 'clayworks:chiseled_bricks')
  event.add('auditory:dirt_sounds', 'caverns_and_chasms:rocky_dirt')
  event.add('auditory:plant_sounds', 'atmospheric:agave', 'environmental:dwarf_spruce', 'environmental:dwarf_spruce_torch', 'environmental:dwarf_spruce_cupric_torch', 'environmental:dwarf_spruce_ender_torch', 'environmental:dwarf_spruce_soul_torch', 'environmental:dwarf_spruce_plant', 'environmental:dwarf_spruce_plant_torch', 'environmental:dwarf_spruce_plant_cupric_torch', 'environmental:dwarf_spruce_plant_ender_torch', 'environmental:dwarf_spruce_plant_soul_torch', '#minecraft:small_flowers', 'upgrade_aquatic:beachgrass', 'upgrade_aquatic:tall_beachgrass', 'minecraft:large_fern', 'environmental:giant_tall_grass', 'farmersdelight:wild_rice', '#minecraft:tall_flowers', 'atmospheric:aloe_bundle')
  event.add('auditory:small_object_sounds', 'supplementaries:goblet', '#minecraft:wooden_buttons', 'windswept:pinecone', 'caverns_and_chasms:cupric_torch', 'endergetic:ender_torch', 'caverns_and_chasms:cupric_wall_torch', 'endergetic:ender_wall_torch', 'upgrade_aquatic:pink_jelly_torch', 'upgrade_aquatic:purple_jelly_torch', 'upgrade_aquatic:blue_jelly_torch', 'upgrade_aquatic:green_jelly_torch', 'upgrade_aquatic:yellow_jelly_torch', 'upgrade_aquatic:orange_jelly_torch', 'upgrade_aquatic:red_jelly_torch', 'upgrade_aquatic:white_jelly_torch', 'upgrade_aquatic:pink_jelly_wall_torch', 'upgrade_aquatic:purple_jelly_wall_torch', 'upgrade_aquatic:blue_jelly_wall_torch', 'upgrade_aquatic:green_jelly_wall_torch', 'upgrade_aquatic:yellow_jelly_wall_torch', 'upgrade_aquatic:orange_jelly_wall_torch', 'upgrade_aquatic:red_jelly_wall_torch', 'upgrade_aquatic:white_jelly_wall_torch', 'windswept:fairy_light', 'windswept:soul_fairy_light', 'windswept:cupric_fairy_light', 'windswept:ender_fairy_light', 'minecraft:lever', 'upgrade_aquatic:elder_eye', 'minecraft:ladder', 'windswept:holly_ladder', 'windswept:chestnut_ladder', 'windswept:pine_ladder', 'quark:bamboo_ladder', 'environmental:willow_ladder', 'environmental:cherry_ladder', 'environmental:wisteria_ladder', 'caverns_and_chasms:azalea_ladder', 'woodworks:spruce_ladder', 'woodworks:birch_ladder', 'woodworks:dark_oak_ladder', 'woodworks:crimson_ladder', 'woodworks:warped_ladder', 'upgrade_aquatic:driftwood_ladder', 'upgrade_aquatic:river_ladder', 'autumnity:maple_ladder', 'atmospheric:rosewood_ladder', 'atmospheric:morado_ladder', 'atmospheric:aspen_ladder', 'atmospheric:laurel_ladder', 'atmospheric:kousa_ladder', 'atmospheric:grimwood_ladder', 'atmospheric:yucca_ladder', '#minecraft:wooden_pressure_plates', '#minecraft:signs')
  event.add('auditory:obsidian_sounds', 'cataclysm:alter_of_abyss')
  event.add('auditory:stone_ore_sounds', 'sullysmod:jade_ore', 'create:zinc_ore', 'caverns_and_chasms:silver_ore', 'caverns_and_chasms:spinel_ore')
  event.add('auditory:metal_sounds', 'quark:iron_button', 'caverns_and_chasms:silver_button', 'caverns_and_chasms:silver_block', 'caverns_and_chasms:silver_bars', 'supplementaries:silver_trapdoor', 'supplementaries:silver_door', 'caverns_and_chasms:medium_weighted_pressure_plate', 'supplementaries:wind_vane', 'quark:iron_plate', 'quark:iron_plate_slab', 'quark:iron_plate_stairs', 'quark:rusty_iron_plate', 'quark:rusty_iron_plate_slab', 'quark:rusty_iron_plate_stairs', 'quark:iron_pillar', 'quark:iron_ladder', 'create:mechanical_press', 'create:crushing_wheel', 'create:andesite_bars', 'create:zinc_block', 'create:brass_funnel', 'create:brass_tunnel', 'create:andesite_funnel', 'create:andesite_tunnel', 'create:empty_blaze_burner', 'create:blaze_burner', 'create:rotation_speed_controller', 'create:mechanical_arm', 'create:mechanical_drill', 'create:redstone_contact', 'create:mechanical_harvester', 'create:mechanical_plough', 'create:mechanical_mixer', 'create:mechanical_bearing', 'create:contraption_controls', 'create:encased_fan', 'create:elevator_pulley', 'caverns_and_chasms:sanguine_plates', 'caverns_and_chasms:sanguine_plate_stairs', 'caverns_and_chasms:sanguine_plate_slab', 'kubejs:grave_metal_plates', 'kubejs:grave_metal_plate_stairs', 'kubejs:grave_metal_plate_slab')
  event.add('auditory:gold_sounds', 'quark:gold_button', 'caverns_and_chasms:golden_bars', 'supplementaries:gold_trapdoor', 'supplementaries:gold_door', 'savage_and_ravage:blast_proof_plates', 'savage_and_ravage:blast_proof_stairs', 'savage_and_ravage:blast_proof_slab')
  event.add('auditory:raw_ore_block_sounds', 'caverns_and_chasms:raw_silver_block', 'create:raw_zinc_block', 'kubejs:raw_silver_bricks', 'kubejs:raw_silver_brick_stairs', 'kubejs:raw_silver_brick_slab', 'kubejs:raw_zinc_bricks', 'kubejs:raw_zinc_brick_stairs', 'kubejs:raw_zinc_brick_slab', 'quark:raw_iron_bricks', 'quark:raw_iron_bricks_stairs', 'quark:raw_iron_bricks_slab', 'quark:raw_copper_bricks', 'quark:raw_copper_bricks_stairs', 'quark:raw_copper_bricks_slab', 'quark:raw_gold_bricks', 'quark:raw_gold_bricks_stairs', 'quark:raw_gold_bricks_slab')
  event.add('auditory:gourd_sounds', 'autumnity:large_pumpkin_slice', 'autumnity:carved_large_pumpkin_slice', 'autumnity:soul_jack_o_lantern', 'autumnity:ender_jack_o_lantern', 'autumnity:cupric_jack_o_lantern', 'autumnity:large_jack_o_lantern_slice', 'autumnity:large_soul_jack_o_lantern_slice', 'autumnity:large_cupric_jack_o_lantern_slice', 'autumnity:large_ender_jack_o_lantern_slice', 'neapolitan:banana_bundle', 'atmospheric:yucca_bundle', 'atmospheric:roasted_yucca_bundle')
  event.add('auditory:lily_pad_sounds', 'environmental:large_lily_pad', 'environmental:giant_lily_pad')
  event.add('auditory:ice_sounds', 'windswept:ice_sheet', 'windswept:packed_ice_stairs', 'windswept:packed_ice_slab', 'windswept:packed_ice_bricks', 'windswept:chiseled_packed_ice_bricks', 'windswept:packed_ice_brick_stairs', 'windswept:packed_ice_brick_slab', 'windswept:packed_ice_brick_wall', 'windswept:blue_ice_stairs', 'windswept:blue_ice_slab', 'windswept:blue_ice_bricks', 'windswept:chiseled_blue_ice_bricks', 'windswept:blue_ice_brick_stairs', 'windswept:blue_ice_brick_slab', 'windswept:blue_ice_brick_wall', 'windswept:icicle_block', 'windswept:chiseled_icicle_block', 'windswept:icicle_door', 'windswept:icicle_trapdoor', 'windswept:icicle_bars')
  event.add('auditory:mushroom_sounds', 'quark:glow_shroom_block')
  event.add('auditory:mushroom_stem_sounds', 'quark:glow_shroom_stem')
  event.add('auditory:stone_brick_sounds', 'windswept:dry_mossy_stone_bricks', 'windswept:dry_mossy_stone_brick_stairs', 'windswept:dry_mossy_stone_brick_slab', 'windswept:dry_mossy_stone_brick_wall', 'upgrade_aquatic:kelpy_stone_bricks', 'upgrade_aquatic:kelpy_stone_brick_stairs', 'upgrade_aquatic:kelpy_stone_brick_slab', 'upgrade_aquatic:kelpy_stone_brick_wall')
  event.add('auditory:terracotta_sounds', 'clayworks:terracotta_stairs', 'clayworks:terracotta_slab', 'clayworks:terracotta_wall', 'clayworks:terracotta_bricks', 'clayworks:terracotta_brick_stairs', 'clayworks:terracotta_brick_slab', 'clayworks:terracotta_brick_wall', 'clayworks:chiseled_terracotta_bricks', 'clayworks:white_terracotta_stairs', 'clayworks:white_terracotta_slab', 'clayworks:white_terracotta_wall', 'clayworks:white_terracotta_bricks', 'clayworks:white_terracotta_brick_stairs', 'clayworks:white_terracotta_brick_slab', 'clayworks:white_terracotta_brick_wall', 'clayworks:chiseled_white_terracotta_bricks', 'clayworks:orange_terracotta_stairs', 'clayworks:orange_terracotta_slab', 'clayworks:orange_terracotta_wall', 'clayworks:orange_terracotta_bricks', 'clayworks:orange_terracotta_brick_stairs', 'clayworks:orange_terracotta_brick_slab', 'clayworks:orange_terracotta_brick_wall', 'clayworks:chiseled_orange_terracotta_bricks', 'clayworks:magenta_terracotta_stairs', 'clayworks:magenta_terracotta_slab', 'clayworks:magenta_terracotta_wall', 'clayworks:magenta_terracotta_bricks', 'clayworks:magenta_terracotta_brick_stairs', 'clayworks:magenta_terracotta_brick_slab', 'clayworks:magenta_terracotta_brick_wall', 'clayworks:chiseled_magenta_terracotta_bricks', 'clayworks:light_blue_terracotta_stairs', 'clayworks:light_blue_terracotta_slab', 'clayworks:light_blue_terracotta_wall', 'clayworks:light_blue_terracotta_bricks', 'clayworks:light_blue_terracotta_brick_stairs', 'clayworks:light_blue_terracotta_brick_slab', 'clayworks:light_blue_terracotta_brick_wall', 'clayworks:chiseled_light_blue_terracotta_bricks', 'clayworks:yellow_terracotta_stairs', 'clayworks:yellow_terracotta_slab', 'clayworks:yellow_terracotta_wall', 'clayworks:yellow_terracotta_bricks', 'clayworks:yellow_terracotta_brick_stairs', 'clayworks:yellow_terracotta_brick_slab', 'clayworks:yellow_terracotta_brick_wall', 'clayworks:chiseled_yellow_terracotta_bricks', 'clayworks:lime_terracotta_stairs', 'clayworks:lime_terracotta_slab', 'clayworks:lime_terracotta_wall', 'clayworks:lime_terracotta_bricks', 'clayworks:lime_terracotta_brick_stairs', 'clayworks:lime_terracotta_brick_slab', 'clayworks:lime_terracotta_brick_wall', 'clayworks:chiseled_lime_terracotta_bricks', 'clayworks:pink_terracotta_stairs', 'clayworks:pink_terracotta_slab', 'clayworks:pink_terracotta_wall', 'clayworks:pink_terracotta_bricks', 'clayworks:pink_terracotta_brick_stairs', 'clayworks:pink_terracotta_brick_slab', 'clayworks:pink_terracotta_brick_wall', 'clayworks:chiseled_pink_terracotta_bricks', 'clayworks:gray_terracotta_stairs', 'clayworks:gray_terracotta_slab', 'clayworks:gray_terracotta_wall', 'clayworks:gray_terracotta_bricks', 'clayworks:gray_terracotta_brick_stairs', 'clayworks:gray_terracotta_brick_slab', 'clayworks:gray_terracotta_brick_wall', 'clayworks:chiseled_gray_terracotta_bricks', 'clayworks:light_gray_terracotta_stairs', 'clayworks:light_gray_terracotta_slab', 'clayworks:light_gray_terracotta_wall', 'clayworks:light_gray_terracotta_bricks', 'clayworks:light_gray_terracotta_brick_stairs', 'clayworks:light_gray_terracotta_brick_slab', 'clayworks:light_gray_terracotta_brick_wall', 'clayworks:chiseled_light_gray_terracotta_bricks', 'clayworks:cyan_terracotta_stairs', 'clayworks:cyan_terracotta_slab', 'clayworks:cyan_terracotta_wall', 'clayworks:cyan_terracotta_bricks', 'clayworks:cyan_terracotta_brick_stairs', 'clayworks:cyan_terracotta_brick_slab', 'clayworks:cyan_terracotta_brick_wall', 'clayworks:chiseled_cyan_terracotta_bricks', 'clayworks:purple_terracotta_stairs', 'clayworks:purple_terracotta_slab', 'clayworks:purple_terracotta_wall', 'clayworks:purple_terracotta_bricks', 'clayworks:purple_terracotta_brick_stairs', 'clayworks:purple_terracotta_brick_slab', 'clayworks:purple_terracotta_brick_wall', 'clayworks:chiseled_purple_terracotta_bricks', 'clayworks:blue_terracotta_stairs', 'clayworks:blue_terracotta_slab', 'clayworks:blue_terracotta_wall', 'clayworks:blue_terracotta_bricks', 'clayworks:blue_terracotta_brick_stairs', 'clayworks:blue_terracotta_brick_slab', 'clayworks:blue_terracotta_brick_wall', 'clayworks:chiseled_blue_terracotta_bricks', 'clayworks:brown_terracotta_stairs', 'clayworks:brown_terracotta_slab', 'clayworks:brown_terracotta_wall', 'clayworks:brown_terracotta_bricks', 'clayworks:brown_terracotta_brick_stairs', 'clayworks:brown_terracotta_brick_slab', 'clayworks:brown_terracotta_brick_wall', 'clayworks:chiseled_brown_terracotta_bricks', 'clayworks:green_terracotta_stairs', 'clayworks:green_terracotta_slab', 'clayworks:green_terracotta_wall', 'clayworks:green_terracotta_bricks', 'clayworks:green_terracotta_brick_stairs', 'clayworks:green_terracotta_brick_slab', 'clayworks:green_terracotta_brick_wall', 'clayworks:chiseled_green_terracotta_bricks', 'clayworks:red_terracotta_stairs', 'clayworks:red_terracotta_slab', 'clayworks:red_terracotta_wall', 'clayworks:red_terracotta_bricks', 'clayworks:red_terracotta_brick_stairs', 'clayworks:red_terracotta_brick_slab', 'clayworks:red_terracotta_brick_wall', 'clayworks:chiseled_red_terracotta_bricks', 'clayworks:black_terracotta_stairs', 'clayworks:black_terracotta_slab', 'clayworks:black_terracotta_wall', 'clayworks:black_terracotta_bricks', 'clayworks:black_terracotta_brick_stairs', 'clayworks:black_terracotta_brick_slab', 'clayworks:black_terracotta_brick_wall', 'clayworks:chiseled_black_terracotta_bricks', 'windswept:gingerbread_block', 'windswept:glazed_gingerbread_block', 'windswept:gingerbread_cookie_block', 'windswept:gingerbread_door', 'windswept:gingerbread_trapdoor', 'windswept:gingerbread_bricks', 'windswept:gingerbread_brick_stairs', 'windswept:gingerbread_brick_slab', 'windswept:gingerbread_brick_wall', 'windswept:glazed_gingerbread_bricks', 'windswept:glazed_gingerbread_brick_stairs', 'windswept:glazed_gingerbread_brick_slab', 'windswept:glazed_gingerbread_brick_wall')

  event.add('minecraft:snow', 'architects_palette:coarse_snow')
  event.add('quark:hedges', 'atmospheric:green_aspen_hedge')
  event.add('caverns_and_chasms:cupric_fire_base_blocks', 'quark:raw_copper_bricks', 'quark:raw_copper_bricks_stairs', 'quark:raw_copper_bricks_slab')
  event.add('endergetic:ender_fire_base_blocks', 'minecraft:amethyst_block', 'minecraft:budding_amethyst', 'caverns_and_chasms:amethyst_block', 'caverns_and_chasms:cut_amethyst', 'caverns_and_chasms:cut_amethyst_bricks', 'caverns_and_chasms:cut_amethyst_brick_slab', 'caverns_and_chasms:cut_amethyst_brick_stairs', 'minecraft:crying_obsidian')
  event.add('alexsmobs:crow_fears', 'windswept:carved_pinecone_block', 'windswept:will_o_the_wisp', 'autumnity:soul_jack_o_lantern', 'autumnity:large_soul_jack_o_lantern_slice', 'autumnity:cupric_jack_o_lantern', 'autumnity:large_cupric_jack_o_lantern_slice', 'autumnity:large_jack_o_lantern_slice', 'autumnity:carved_large_pumpkin_slice', 'autumnity:ender_jack_o_lantern', 'autumnity:large_ender_jack_o_lantern_slice')

  event.remove('minecraft:needs_diamond_tool', 'irons_spellbooks:armor_pile')
  event.remove('create:windmill_sails', '#minecraft:wool')

  // needs_stone = iron, needs_wood = copper, needs_iron = gold/silver
  event.get('minecraft:needs_stone_tool').getObjectIds().forEach(block => {
    if (Ingredient.of(/.*copper.*/).test(block)) 
      event.remove('minecraft:needs_stone_tool', block)
    else if (Ingredient.of(/.*iron.*/).test(block)) {
      event.remove('minecraft:needs_stone_tool', block)
      event.add('minecraft:needs_wooden_tool', block)
    }
  })
  event.get('minecraft:needs_iron_tool').getObjectIds().forEach(block => {
    if (Ingredient.of(/.*zinc.*/).test(block)) {
      event.remove('minecraft:needs_iron_tool', block)
      event.add('minecraft:needs_wooden_tool', block)
    } else if (Ingredient.of(/.*gold.*/).test(block)) {
      event.remove('minecraft:needs_iron_tool', block)
      event.add('minecraft:needs_stone_tool', block)
    } else if (Ingredient.of(/.*silver.*/).test(block)) {
      event.remove('minecraft:needs_iron_tool', block)
      event.add('minecraft:needs_stone_tool', block)
    }
  })
  event.get('minecraft:mineable/pickaxe').getObjectIds().forEach(block => {
    if (Ingredient.of(/.*deepslate.*/).test(block)) {
      if (!event.get('minecraft:needs_iron_tool').getObjectIds().contains(block) && !event.get('minecraft:needs_diamond_tool').getObjectIds().contains(block)) event.add('minecraft:needs_stone_tool', block)
      if (event.get('minecraft:needs_wooden_tool').getObjectIds().contains(block)) event.remove('minecraft:needs_wooden_tool', block)
      if (event.get('minecraft:needs_wooden_tool').getObjectIds().contains(block)) event.remove('minecraft:needs_wooden_tool', block)
    }
  })
})

ServerEvents.tags('worldgen/biome', event => {
  event.removeAll('minecraft:has_structure/village_desert')
  event.removeAll('minecraft:has_structure/village_plains')
  event.removeAll('minecraft:has_structure/village_savanna')
  event.removeAll('minecraft:has_structure/village_snowy')
  event.removeAll('minecraft:has_structure/village_taiga')
  event.removeAll('minecraft:has_structure/pillager_outpost')
  event.removeAll('minecraft:has_structure/woodland_mansion')
  event.removeAll('atmospheric:has_structure/village_scrubland')
  event.removeAll('windswept:has_structure/frozen_village')
  event.removeAll('autumnity:has_structure/maple_hut')
  event.removeAll('environmental:has_animal/cow')
  event.removeAll('upgrade_aquatic:has_animal/pike_extra')
  event.removeAll('neapolitan:has_feature/mint_pond')
  event.removeAll('neapolitan:has_feature/adzuki_sprouts')
  event.removeAll('sullysmod:jade_generates_in')
  event.removeAll('cataclysm:has_structure/ancient_factory_biomes')
  event.removeAll('cataclysm:has_structure/frosted_prison_biomes')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_overgrown')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_desert')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_spruce_snowy')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_ice')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_acacia')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_jungle')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_mesa')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_red_desert')
  event.removeAll('bettermineshafts:has_structure/better_mineshaft_mushroom')
  event.removeAll('betterdungeons:has_structure/spider_dungeon')
  event.removeAll('queen_bee:has_structure/beehive')
  event.removeAll('irons_spellbooks:has_structure/pyromancer_tower')
  event.removeAll('irons_spellbooks:has_structure/evoker_fort')
  event.removeAll('irons_spellbooks:has_structure/mangrove_hut')
  event.removeAll('minecraft:has_structure/ruined_portal_desert')
  event.removeAll('minecraft:has_structure/ruined_portal_jungle')
  event.removeAll('minecraft:has_structure/ruined_portal_mountain')
  event.removeAll('minecraft:has_structure/ruined_portal_ocean')
  event.removeAll('minecraft:has_structure/ruined_portal_standard')
  event.removeAll('minecraft:has_structure/ruined_portal_swamp')
  event.removeAll('atmospheric:has_structure/kousa_sanctum')

  event.add('minecraft:has_structure/ruined_portal_jungle', '#atmospheric:is_rainforest')
  event.add('upgrade_aquatic:has_monster/thrasher', '#minecraft:is_ocean')
  event.add('environmental:has_feature/tasselflower', 'atmospheric:laurel_forest', 'atmospheric:spiny_thicket', 'atmospheric:scrubland', 'atmospheric:snowy_scrubland', 'minecraft:wooded_badlands')
  event.add('forge:is_snowy', 'atmospheric:snowy_scrubland')
  event.add('environmental:has_animal/tapir', '#atmospheric:is_rainforest')
  event.add('minecraft:has_structure/desert_pyramid', '#atmospheric:is_dunes', 'atmospheric:spiny_thicket')
  event.add('neapolitan:has_feature/vanilla_vine', '#atmospheric:is_dunes', '#minecraft:is_badlands', 'atmospheric:spiny_thicket')
  event.add('environmental:has_animal/zebra', '#atmospheric:is_dunes', 'atmospheric:laurel_forest')
  event.add('environmental:has_animal/yak', 'windswept:pine_barrens', 'windswept:chestnut_forest', 'windswept:snowy_chestnut_forest', 'environmental:blossom_woods', 'minecraft:old_growth_pine_taiga', 'atmospheric:kousa_jungle', 'atmospheric:aspen_parkland', 'minecraft:dark_forest', 'windswept:lavender_meadow', 'minecraft:taiga', 'minecraft:snowy_taiga', 'minecraft:old_growth_pine_taiga', 'minecraft:old_growth_spruce_taiga')
  event.remove('upgrade_aquatic:has_animal/pike', 'minecraft:river');
  event.add('upgrade_aquatic:has_animal/perch', 'environmental:marsh');
  event.add('upgrade_aquatic:has_animal/pike', '#atmospheric:is_rainforest');
  event.add('endermanoverhaul:desert_spawns', '#atmospheric:is_dunes')
  event.add('endermanoverhaul:ice_spikes_spawns', '#forge:is_snowy')
  event.add('endermanoverhaul:windswept_hills_spawns', '#forge:is_mountain')
  event.add('endermanoverhaul:dark_oak_spawns', 'minecraft:old_growth_spruce_taiga', 'windswept:pine_barrens', 'minecraft:old_growth_pine_taiga', 'windswept:chestnut_forest', 'atmospheric:aspen_parkland', 'minecraft:old_growth_birch_forest')
  event.remove('endermanoverhaul:windswept_hills_spawns', 'minecraft:meadow', 'windswept:lavender_meadow')
  event.add('minecraft:has_structure/desert_pyramid', 'atmospheric:spiny_thicket', 'atmospheric:petrified_dunes', 'atmospheric:flourishing_dunes', 'atmospheric:dunes', 'atmospheric:rocky_dunes', 'atmospheric:scrubland', 'atmospheric:snowy_scrubland')
  event.add('rrm:has_animal/frog', 'atmospheric:rainforest_basin', 'atmospheric:sparse_rainforest_basin')
  event.add('rrm:has_animal/cat', '#minecraft:is_forest')
  event.add('rrm:has_structure/pine_windmill', 'windswept:pine_barrens')
  event.add('sullysmod:jade_generates_in', 'minecraft:lush_caves')
  event.add('environmental:has_structure/log_cabin', '#windswept:is_pine_barrens')
  event.add('bettermineshafts:has_structure/better_mineshaft_mushroom', 'quark:glimmering_weald')
  event.add('irons_spellbooks:has_structure/pyromancer_tower', '#windswept:is_pine_barrens')
  event.add('alexsmobs:spawns_red_gusters', 'atmospheric:spiny_thicket')
  event.add('alexsmobs:spawns_desert_crocodiles', 'atmospheric:spiny_thicket', '#atmospheric:is_dunes', '#atmospheric:is_rainforest')
  event.add('autumnity:has_feature/spotted_maple_tree/red', 'atmospheric:aspen_parkland')
  event.add('naturalist:has_giraffe', 'atmospheric:laurel_forest', '#atmospheric:is_dunes')

})

ServerEvents.tags('mob_effect', event => {
  event.add('caverns_and_chasms:bejeweled_apple_cannot_inflict', 'cofh_core:cold_resistance', 'cofh_core:explosion_resistance', 'cofh_core:magic_resistance', 'cofh_core:lightning_resistance', 'cofh_core:supercharge', 'cofh_core:clarity', 'cofh_core:love', 'cofh_core:panacea', 'cofh_core:true_invisibility', 'cofh_core:enderference', 'cofh_core:slimed', 'cofh_core:chilled', 'cofh_core:shocked', 'cofh_core:sundered', 'cofh_core:wrenched', 'archers_paradox:challenge_complete', 'archers_paradox:challenge_miss', 'archers_paradox:challenge_streak', 'archers_paradox:training_miss', 'archers_paradox:training_streak', 'alexsmobs:lava_vision', 'alexsmobs:knockback_resistance', 'alexsmobs:sunbird_blessing', 'alexsmobs:sunbird_curse', 'alexsmobs:knockback_resistance', 'alexsmobs:poison_resistance', 'alexsmobs:oiled', 'alexsmobs:orcas_might', 'alexsmobs:bug_pheromones', 'alexsmobs:soulsteal', 'alexsmobs:clinging', 'alexsmobs:ender_flu', 'alexsmobs:fear', 'alexsmobs:tigers_blessing', 'alexsmobs:debilitating_sting', 'alexsmobs:exsanguination', 'alexsmobs:earthquake', 'alexsmobs:fleet_footed', 'alexsmobs:power_down', 'cataclysm:monstrous', 'cataclysm:blazing_brand', 'cataclysm:stun', 'cataclysm:abyssal_burn', 'cataclysm:bone_fracture', 'cataclysm:abyssal_fear', 'cataclysm:abyssal_curse', 'cataclysm:blessing_of_amethyst', 'cataclysm:curse_of_desert', 'cataclysm:ghost_form', 'cataclysm:ghost_sickness', 'supplementaries:overencumbered', 'irons_spellbooks:angel_wings', 'irons_spellbooks:evasion', 'irons_spellbooks:heartstop', 'irons_spellbooks:vex_timer', 'irons_spellbooks:polar_bear_timer', 'irons_spellbooks:raise_dead_timer', 'irons_spellbooks:summon_horse_timer', 'irons_spellbooks:abyssal_shroud', 'irons_spellbooks:ascension', 'irons_spellbooks:charged', 'irons_spellbooks:true_invisibility', 'irons_spellbooks:fortify', 'irons_spellbooks:rend', 'irons_spellbooks:spider_aspect', 'irons_spellbooks:blight', 'irons_spellbooks:guided', 'irons_spellbooks:airborne', 'irons_spellbooks:vigor', 'irons_spellbooks:instant_mana', 'irons_spellbooks:oakskin', 'irons_spellbooks:planar_sight', 'irons_spellbooks:antigravity', 'irons_spellbooks:hastened', 'irons_spellbooks:slowed', 'irons_spellbooks:chilled', 'irons_spellbooks:burning_dash', 'irons_spellbooks:gluttony', 'irons_spellbooks:echoing_strikes', 'irons_spellbooks:thunderstorm', 'savage_and_ravage:weight', 'upgrade_aquatic:insomnia', 'clash:rampaging', 'clash:retaliation', 'clash:staggered', 'neapolitan:sugar_rush', 'neapolitan:harmony', 'autumnity:extension', 'environmental:panic', 'environmental:serenity', 'buzzier_bees:sunny', 'upgrade_aquatic:restfulness', 'minecraft:conduit_power', 'minecraft:dolphins_grace', 'neapolitan:berserking', 'farmersdelight:nourishment', 'quark:resilience', 'undead_unleashed:flame_breathing', 'undead_unleashed:shadow_form', 'undead_unleashed:skill_exhaustion', 'undead_unleashed:skill_exhaustion_1', 'undead_unleashed:skill_exhaustion_2', 'undead_unleashed:skill_exhaustion_4', 'undead_unleashed:grounded', 'undead_unleashed:spirit_protection', 'atmospheric:spitting', 'neapolitan:slipping')
})

ServerEvents.tags('worldgen/structure', event => {
  event.removeAll('minecraft:eye_of_ender_located')
  event.add('minecraft:eye_of_ender_located', 'minecraft:ancient_city')
})

ServerEvents.tags('worldgen/template_pool', event => {
  event.add('structure_no_rotate:do_not_rotate', 'rrm:floating_island')
})