ItemEvents.tooltip(event => {
  event.add(['minecraft:ender_eye'], "§7Locates the Ancient City")
  event.add(['cataclysm:monstrous_eye'], "§7Locates the Soul Black Smith")
  event.add(['cataclysm:abyss_eye'], "§7Locates the Sunken City")
  event.add(['cataclysm:flame_eye'], "§7Locates the Burning Arena")
  event.add(['spelunkery:portal_fluid_bottle'], "§7Drink to return to your Spawnpoint")
  event.add(['spelunkery:rough_lazurite', 'spelunkery:rough_diamond', 'sullysmod:rough_jade', 'kubejs:rough_spinel'], "§7Polishable with Sand Paper")
  event.add(['clash:greatblade'], " §9+1 Staggering Infliction")
  event.add(['queen_bee:stinger_sword'], " §9+1 Poison Infliction")
  event.add(['cataclysm:abyssal_sacrifice'], "§7Offer to the Altar of Abyss to summon the Leviathan")
  event.add(['cataclysm:burning_ashes'], "§7Offer to the Altar of Fire to summon Ignis")
  event.add(['minecraft:dark_oak_sapling', 'atmospheric:grimwood_sapling'], "§7Must be grown in 2x2 shape")
  event.addAdvanced('clash:rod_of_gales', (item, advanced, text) => text.add(1, Text.of("§7Hold and release R-Click when grounded to propel yourself")))
  event.addAdvanced('minecraft:wooden_pickaxe', (item, advanced, text) => text.add(1, Text.of("§7Can Mine: Stone, Coal, Copper")))
  event.addAdvanced('metalworks:copper_pickaxe', (item, advanced, text) => text.add(1, Text.of("§7Can Mine: Iron, Zinc")))
  event.addAdvanced('minecraft:iron_pickaxe', (item, advanced, text) => text.add(1, Text.of("§7Can Mine: Gold, Silver, Deepslate")))
  event.addAdvanced(['minecraft:golden_pickaxe', 'caverns_and_chasms:silver_pickaxe'], (item, advanced, text) => text.add(1, Text.of("§7Can Mine: Diamond")))
  event.addAdvanced('minecraft:diamond_pickaxe', (item, advanced, text) => text.add(1, Text.of("§7Can Mine: Obsidian, Ancient Debris")))
  event.addAdvanced('minecraft:trident', (item, advanced, text) => text.add(1, Text.of("§7Trident will return to you after thrown")))
  event.addAdvanced('mace_backport:mace', (item, advanced, text) => text.add(1, Text.of("§7Emits a burst of wind upon hitting an enemy")))
  event.addAdvanced('mace_backport:mace', (item, advanced, text) => text.add(1, Text.of("§7Hit enemies will be flung into the air")))
})
