[[curiosSettings]]
identifier = "head"
  visible = false
  locked = true
[[curiosSettings]]
identifier = "back"
  visible = false
  locked = true
[[curiosSettings]]
identifier = "charm"
  visible = false
  locked = true
[[curiosSettings]]
identifier = "spyglass"
  visible = false
  locked = true

