
["Aileron Forge Config"]

	["Aileron Forge Config"."Camera Settings"]
		#Enable camera roll
		doCameraRoll = false
		#Camera Roll Scale
		cameraRollScale = 1.0
		#Camera Roll Speed
		cameraRollSpeed = 0.1

