#Changes the Creeper Overhaul creepers to destroy blocks or not.
destroyBlocks = true

[client]
	#Change the Vanilla Creeper to a new and improved texture with better animations.
	replaceDefaultCreeper = false

[spawning]
	#Change the Creeper Overhaul creepers to spawn or not.
	allowSpawning = true
	#Change the Jungle Creeper to spawn or not.
	allowJungleCreeperSpawning = false
	#Change the Bamboo Creeper to spawn or not.
	allowBambooCreeperSpawning = true
	#Change the Desert Creeper to spawn or not.
	allowDesertCreeperSpawning = true
	#Change the Badlands Creeper to spawn or not.
	allowBadlandsCreeperSpawning = true
	#Change the Hills Creeper to spawn or not.
	allowHillsCreeperSpawning = true
	#Change the Savannah Creeper to spawn or not.
	allowSavannahCreeperSpawning = false
	#Change the Mushroom Creeper to spawn or not.
	allowMushroomCreeperSpawning = false
	#Change the Swamp Creeper to spawn or not.
	allowSwampCreeperSpawning = true
	#Change the Dripstone Creeper to spawn or not.
	allowDripstoneCreeperSpawning = false
	#Change the Cave Creeper to spawn or not.
	allowCaveCreeperSpawning = false
	#Change the Dark Oak Creeper to spawn or not.
	allowDarkOakCreeperSpawning = true
	#Change the Spruce Creeper to spawn or not.
	allowSpruceCreeperSpawning = true
	#Change the Beach Creeper to spawn or not.
	allowBeachCreeperSpawning = false
	#Change the Snowy Creeper to spawn or not.
	allowSnowyCreeperSpawning = true
	#Change the Ocean Creeper to spawn or not.
	allowOceanCreeperSpawning = false

