
#Changes to item tooltips
[tooltips]
	#Items that are dyeable with have a tooltip displaying this
	"Dyeable Tooltip" = true
	#All Horse Armour items will display their armor stat
	"Horse Armour Tooltip" = true
	#Food Item Tooltips display which effects they provide
	"Food Effect Tooltip" = true
	#Blacklist of items to display food effects tooltips
	"Food Effect Tooltip BlackList" = ["farmersdelight:apple_cider", "farmersdelight:cooked_rice", "farmersdelight:bone_broth", "farmersdelight:beef_stew", "farmersdelight:chicken_soup", "farmersdelight:vegetable_soup", "farmersdelight:fish_stew", "farmersdelight:fried_rice", "farmersdelight:pumpkin_soup", "farmersdelight:baked_cod_stew", "farmersdelight:noodle_soup", "farmersdelight:bacon_and_eggs", "farmersdelight:pasta_with_meatballs", "farmersdelight:pasta_with_mutton_chop", "farmersdelight:mushroom_rice", "farmersdelight:roasted_mutton_chops", "farmersdelight:vegetable_noodles", "farmersdelight:steak_and_potatoes", "farmersdelight:ratatouille", "farmersdelight:squid_ink_pasta", "farmersdelight:grilled_salmon", "farmersdelight:roast_chicken", "farmersdelight:stuffed_pumpkin", "farmersdelight:honey_glazed_ham", "farmersdelight:shepherds_pie", "farmersdelight:fruit_salad", "farmersdelight:mixed_salad", "abnormals_delight:slabdish", "miners_delight:cave_soup"]
	#Items In this list will have a custom tooltip you will have to add a translation for
	"Custom Tooltip List" = ["kubejs:lead_dust=brewing_ingredient", "atmospheric:yucca_branch=brewing_ingredient", "kubejs:silver_feather=brewing_ingredient", "quark:glow_shroom=brewing_ingredient", "cataclysm:lionfish=brewing_ingredient", "undead_unleashed:lost_soul=brewing_ingredient", "architects_palette:withered_bone=brewing_ingredient", "alexsmobs:bone_serpent_tooth=brewing_ingredient", "unusualfishmod:raw_snowflake=brewing_ingredient"]
	#Items that can be brewed into a potion will have a tooltip saying "Brewing Ingredient"; default: false
	"Brewing Ingredient Tooltip" = true
	#Blacklist of items to display brewing ingredient tooltip
	"Brewing Ingredient Tooltip BlackList" = ["caverns_and_chasms:bejeweled_pearl", "minecraft:amethyst_cluster", "minecraft:blaze_powder", "oreganized:lead_ingot"]
	#Appends the Tooltip of a Music Disc to also display the Length of the Song
	"Music Disc Tooltip" = true
	#Displays the Mining Level of the Pickaxe as a Percentage
	"Pickaxe Mining Power" = true
	#Displays the Mining Speed of the Tool
	"Tool Mining Speed" = true
	#If Items hidden with fermion should contain a tooltip displaying that the item is hidden.
	"Hidden Item Tooltip" = true
	#List of items to hide the Attack Damage & Attack Speed Tooltips for.
	"Hide Damage & Speed" = ["minecraft:wooden_pickaxe", "minecraft:golden_pickaxe", "minecraft:iron_pickaxe", "minecraft:diamond_pickaxe", "minecraft:netherite_pickaxe", "metalworks:copper_pickaxe", "caverns_and_chasms:silver_pickaxe", "caverns_and_chasms:necromium_pickaxe", "minecraft:wooden_axe", "minecraft:golden_axe", "minecraft:iron_axe", "minecraft:diamond_axe", "minecraft:netherite_axe", "metalworks:copper_axe", "caverns_and_chasms:silver_axe", "caverns_and_chasms:necromium_axe", "undead_unleashed:grave_metal_axe", "minecraft:wooden_shovel", "minecraft:golden_shovel", "minecraft:iron_shovel", "minecraft:diamond_shovel", "minecraft:netherite_shovel", "metalworks:copper_shovel", "caverns_and_chasms:silver_shovel", "caverns_and_chasms:necromium_shovel"]
	#Makes all attribute item tooltips unifrmly the same dark green colour; default: false
	"Uniform Attribute Colour" = true

