placeSnowInBlock = true
placeSnowInBlockNaturally = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = false
snowAccumulationMaxLayers = 1
thinnerBoundingBox = true
snowMakingIce = true
snowNeverMelt = false
snowAndIceMeltInWarmBiomes = false
snowNaturalMelt = true
snowReduceFallDamage = false
replaceWorldFeature = false
sustainGrassIfLayerMoreThanOne = true
retainOriginalBlocks = false
sneakSnowball = true
mobSpawningMaxLayers = 8

[integration]
accumulationWinterOnly = false

[debug]
weatherTickSlowness = 16
mobSpawningCommand = false
